### ISSUE TITLE
[CRASH] crash when generating new chunks.

### ISSUE THREAD

**Issue by meelock** [mcenderdragon/Futurepack-API#123]
here is the short version: 

java.lang.NumberFormatException: For input string: "fffffffdffffffec"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:592)
	at java.lang.Long.valueOf(Long.java:776)
	at java.lang.Long.decode(Long.java:928)
	at futurepack.common.FPDungeonProtection$DungeonProtection.loadQueed(FPDungeonProtection.java:215)
	at futurepack.common.FPDungeonProtection$DungeonProtection.onChunkOpen(FPDungeonProtection.java:284)
	at futurepack.common.FPDungeonProtection.onChunkOpen(FPDungeonProtection.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1557_FPDungeonProtection_onChunkOpen_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:98)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

here is the pastebin:
[(most of it)](http://pastebin.com/KDx2s3Qz)

**Comment by mcenderdragon** [comment]
so you just entered the world and it crashed ?

**Comment by meelock** [comment]
Don't quote me on this, but this crash only happens when generating one of fp's dungeons. So what happened was, I explored for a bit, then crashed.

**Comment by meelock** [comment]
I may try testing said core mods in a bit, if you do not respond with anything... :P

**Comment by DeadSix27** [comment]
Same issue here, happened during world generation:

Stacktrace: http://pastebin.com/JwnfxV4A

**Comment by mcenderdragon** [comment]
Ok I found out what is causing this, somehow java is unable to decode long hexcode of negative values, thats why it crashes.

**Comment by mcenderdragon** [comment]
Does [this](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.115) version fix the bug ?

**Comment by meelock** [comment]
when loading the world, i instead got this:

java.lang.NullPointerException: Exception in server tick loop
	at futurepack.common.FPDungeonProtection$DungeonProtection$ProtectionData.deserializeNBT(FPDungeonProtection.java:413)
	at futurepack.common.FPDungeonProtection$DungeonProtection.loadQueed(FPDungeonProtection.java:220)
	at futurepack.common.FPDungeonProtection$DungeonProtection.onChunkOpen(FPDungeonProtection.java:284)
	at futurepack.common.FPDungeonProtection.onChunkOpen(FPDungeonProtection.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1561_FPDungeonProtection_onChunkOpen_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:98)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mcenderdragon** [comment]
Ok, I think [this Version](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.116) should also fix that problem.

**Comment by meelock** [comment]
and... the server appears to be down...

**Comment by meelock** [comment]
the server appears to be slow/down

**Comment by DeadSix27** [comment]
@meelock works fine on my end, might be a routing issue (its a German server and I assume you are not german)

**Comment by meelock** [comment]
its still failing due to a networking error, eg its being slow... can you host it on another site, such as dropbox?

**Comment by mcenderdragon** [comment]
Well our server is up and running fine with excelent speed, but shure: [Mediafire](http://www.mediafire.com/file/qdw5uba5div65v8/Futurepack-1.10.2-24.2.116.jar)

**Comment by meelock** [comment]
this issue appears to be fixed, thanks!
