### ISSUE TITLE
Unable to connect to server - NPE - FPPacketHandler

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#245]
When trying to connect to the server, I get this disconnection when trying to connect.

[23:06:10] [Netty Client IO #5/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraft.client.multiplayer.WorldClient.func_73045_a(WorldClient.java:270) ~[bsb.class:?]
	at futurepack.common.sync.FPPacketHandler$MessageFPData.onMessage(FPPacketHandler.java:787) ~[FPPacketHandler$MessageFPData.class:?]
	at futurepack.common.sync.FPPacketHandler$MessageFPData.onMessage(FPPacketHandler.java:764) ~[FPPacketHandler$MessageFPData.class:?]

Client log - https://gist.github.com/ProsperCraft/aba0c9f51746b18aab55809392b9dfaa

Server console- https://gist.github.com/ProsperCraft/8233af80ab09eecc1021d55232d1e96b

**Comment by mcenderdragon** [comment]
This crash is caused by forges broken netty. Does this always happen or only sometimes.

**Comment by ProsperCraft** [comment]
Only sometimes, perhaps future forge updates will fix it, will re-open if it happens again.

**Comment by mcenderdragon** [comment]
ok
