### ISSUE TITLE
Weird crash in forscher gui

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#27]
oRginaL: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2644868-futurepack-mod-discover-new-dimensions?page=9#c173

crash:
`java.lang.NullPointerException: Rendering screen
at futurepack.common.gui.GuiForscher.getUUID(GuiForscher.java:189)
at futurepack.common.gui.GuiForscher.renderHead(GuiForscher.java:218)
at futurepack.common.gui.GuiForscher.func_146976_a(GuiForscher.java:92)
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by mcenderdragon** [comment]
should be fixed

**Comment by Wugand** [comment]
it works, you can close it
