### ISSUE TITLE
Heuler Entity on Melenus crashes server

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#284]
java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at futurepack.common.entity.EntityHeuler$AIRestOnWater.func_75246_d(EntityHeuler.java:714)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at futurepack.common.entity.EntityHeuler.func_70636_d(EntityHeuler.java:113)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.19) fixes this issue?

**Comment by kingofrunes** [comment]
Looks good to me, thanks!

**Comment by mcenderdragon** [comment]
(I reopen it so i know this isses is fuixed in the next realese, cause crash and stuff...)
