### ISSUE TITLE
FML Log Spam 1.12.2 and Futurepack-1.12.1-26.2.19

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#285]
Recent fml log spam with 1.12.2 and Futurepack-1.12.1-26.2.19 and forge 14.23.0.2512

[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadResource:430]: java.io.FileNotFoundException: fp:lang/en_us/story.kryptographie.json
[07:52:01] [main/ERROR] [Futurepack/]: java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\story.kryptographie.json (The system cannot find the path specified)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\story.kryptographie.json (The system cannot find the path specified)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.open(Native Method)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadResource(ResearchLoader.java:433)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadJson(ResearchLoader.java:340)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.getLocalisated(ResearchLoader.java:299)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ScannerPageResearch.getComponetsFromName(ScannerPageResearch.java:79)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiScannerPageResearch.<init>(GuiScannerPageResearch.java:11)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.openResearchText(GuiResearchMainOverview.java:218)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearch(GuiResearchTreePage.java:220)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearches(GuiResearchTreePage.java:191)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.func_73863_a(GuiResearchTreePage.java:121)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.func_73863_a(GuiResearchMainOverview.java:72)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at Reflector.callVoid(Reflector.java:555)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadResource:430]: java.io.FileNotFoundException: fp:lang/en_us/story.kryptographie.json
[07:52:01] [main/ERROR] [Futurepack/]: java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\story.kryptographie.json (The system cannot find the path specified)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\story.kryptographie.json (The system cannot find the path specified)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.open(Native Method)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadResource(ResearchLoader.java:433)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadJson(ResearchLoader.java:340)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.getLocalisated(ResearchLoader.java:302)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ScannerPageResearch.getComponetsFromName(ScannerPageResearch.java:79)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiScannerPageResearch.<init>(GuiScannerPageResearch.java:11)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.openResearchText(GuiResearchMainOverview.java:218)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearch(GuiResearchTreePage.java:220)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearches(GuiResearchTreePage.java:191)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.func_73863_a(GuiResearchTreePage.java:121)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.func_73863_a(GuiResearchMainOverview.java:72)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at Reflector.callVoid(Reflector.java:555)
[07:52:01] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadResource:430]: java.io.FileNotFoundException: fp:lang/de_de/story.kryptographie.json
[07:52:02] [main/ERROR] [Futurepack/]: java.io.FileNotFoundException: .\mods\futurepack\lang\de_de\story.kryptographie.json (The system cannot find the path specified)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: java.io.FileNotFoundException: .\mods\futurepack\lang\de_de\story.kryptographie.json (The system cannot find the path specified)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.open(Native Method)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadResource(ResearchLoader.java:433)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.loadJson(ResearchLoader.java:340)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ResearchLoader.getLocalisated(ResearchLoader.java:305)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.research.ScannerPageResearch.getComponetsFromName(ScannerPageResearch.java:79)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiScannerPageResearch.<init>(GuiScannerPageResearch.java:11)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.openResearchText(GuiResearchMainOverview.java:218)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearch(GuiResearchTreePage.java:220)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.drawResearches(GuiResearchTreePage.java:191)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchTreePage.func_73863_a(GuiResearchTreePage.java:121)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at futurepack.common.gui.GuiResearchMainOverview.func_73863_a(GuiResearchMainOverview.java:72)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at Reflector.callVoid(Reflector.java:555)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadJson:351]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:52:02] [main/INFO] [STDERR/]: [futurepack.common.research.ResearchLoader:loadResource:430]: java.io.FileNotFoundException: fp:lang/story.kryptographie.json
[07:52:02] [main/ERROR] [Futurepack/]: java.io.FileNotFoundException: .\mods\futurepack\lang\story.kryptographie.json (The system cannot find the path specified)
[07:52:08] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:00:43] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:00:47] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:01:07] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:01:27] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:01:47] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:03:22] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:03:30] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:04:01] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:04:06] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:04:16] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:04:19] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:05:16] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:05:20] [main/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION DATA CLIENTSIDE **
[08:06:59] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:07:11] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:07:31] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:07:54] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:08:59] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:10:56] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:14:02] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:16:34] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:19:06] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:19:40] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:19:58] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:20:14] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:20:24] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:25:20] [main/WARN] [jei/]: Recipe Category lookup is slow: 14 ms. class mezz.jei.recipes.InternalRecipeRegistryPlugin
[08:27:04] [main/WARN] [jei/]: Recipe Wrapper lookup is slow: 15 ms. class binnie.extratrees.integration.jei.multifence.MultiFenceRecipeRegistryPlugin
[08:29:26] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:29:49] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:30:23] [main/INFO] [Futurepack/]: Send Research Request to Server
[08:33:00] [main/INFO] [Futurepack/]: Send Research Request to Server
[09:04:06] [main/INFO] [Futurepack/]: Send Research Request to Server
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null
[09:04:49] [main/INFO] [STDERR/]: [futurepack.depend.api.helper.HelperJSON:getItemFromJSON:143]: ItemStack parsing failed: '""' is null

**Comment by trogarus** [comment]
Also, latest fp log here as well

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1411885/FP-Latest.log)
