### ISSUE TITLE
[1.12.2] Recycler not keeping inventory [Futurepack-1.12.1-26.2.27]

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#293]
Futurepack-1.12.1-26.2.27 MC 1.12.2 and forge 14.23.0.2512 the recycler is not keeping inventory on shutdown or crash. This includes the flash drive inventory, item for recycling inventory, and the tool inventory slots. This was also an issue with last version, which I neglected to mention in my other bug reports here.

**Comment by trogarus** [comment]
Additional log entries (latest game start and stop) with bits about the recycler as well

`java.lang.NullPointerException: null
	at futurepack.common.block.machines.TileEntityRecycler.func_70296_d(TileEntityRecycler.java:604) ~[TileEntityRecycler.class:?]
	at futurepack.common.block.machines.TileEntityMachineBase.func_70299_a(TileEntityMachineBase.java:125) ~[TileEntityMachineBase.class:?]
	at futurepack.common.block.machines.TileEntityMachineBase.func_145839_a(TileEntityMachineBase.java:56) ~[TileEntityMachineBase.class:?]
	at futurepack.common.block.machines.TileEntityRecycler.func_145839_a(TileEntityRecycler.java:480) ~[TileEntityRecycler.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:492) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) [amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:304) [amu.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2379) [amu.class:?]
	at futurepack.common.block.FPBlocks.powerLowestBlock(FPBlocks.java:1294) [FPBlocks.class:?]
	at futurepack.common.block.TileEntityWire.func_73660_a(TileEntityWire.java:103) [TileEntityWire.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1829) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]`

This is after a restart after letting stuff in the recycler on game shutdown.

**Comment by trogarus** [comment]
Full log here

[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1431082/latest.log)
