### ISSUE TITLE
Crash when placing Laser Turret without any connecting Power line

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#302]
java.lang.ArrayIndexOutOfBoundsException: 0
	at futurepack.common.block.TileEntityLaserBase.setConfigFromShort(TileEntityLaserBase.java:420)
	at futurepack.common.block.TileEntityLaserBase.func_145839_a(TileEntityLaserBase.java:442)
	at futurepack.common.block.FPBlocks.placeNBT(FPBlocks.java:1151)
	at futurepack.common.block.BlockHoldingTile.func_180633_a(BlockHoldingTile.java:66)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:476)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by kingofrunes** [comment]
Turns out this problem went away when I laid down the cables first

**Comment by mcenderdragon** [comment]
this crash should not be related to cables or  not... i am digging into it.

**Comment by mcenderdragon** [comment]
THis was caused by a false NBT tag in the item, this should not occure again.
