### ISSUE TITLE
[1.12.2] crafttweaker support in this version?

### ISSUE THREAD

**Issue by jesmores** [mcenderdragon/Futurepack-API#303]
Does FP support crafttweaker in 1.12? I just tried using the `futurepack.industrial.add` function and CT said it couldn't find `futurepack`. I also tried `mods.futurepack.industrial.add` and got the same error.

Forge 14.23.0.2531
FuturePack 1.12.1-26.2.27
CraftTweaker2-1.12-4.0.9
ModTweaker-4.0.5
MTLib-3.0.1

**Comment by mcenderdragon** [comment]
I changed nothign  so it should work.... I am checking it.
It should work, here is a list of supportet stuff: https://github.com/mcenderdragon/Futurepack-API/wiki/Crafttweaker-support

**Comment by jesmores** [comment]
I just tried it on a test instance with _only_ FP, CraftTweaker, ModTweaker, MTLib and JEI installed. Same error.

I used that page to write my script yeah.

Here's the line from test.zs that I tried
```
futurepack.industrial.add(<minecraft:dye:11>, [<minecraft:planks:4>, <minecraft:planks:1>, <minecraft:planks>]);
```
And this is what I got when using `/ct syntax` or restarting the game and loading the world.

```
[08:03:11] [main/INFO]: [CHAT] ERROR: test.zs:1 > could not find futurepack
[08:03:11] [main/INFO]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: test.zs}: 1

```

**Comment by mcenderdragon** [comment]
hmm ok, can you give me the fml-client latest, eraly junk, FP-latest.log, and everything else that is somehow in your log ?

**Comment by mcenderdragon** [comment]
I know hwat has happend, in the 1.12. version crafttweaker renamed everything -.-

**Comment by jesmores** [comment]
Here are my logs: https://gist.github.com/jesmores/4d5e7374993bd04e5e708ecc5910996c

That's a world with the test.zs I describe above, and also a regular CT recipe tweak to do the same with but as a shapeless recipe with the crafting table.

I started minecraft, deleted my old test world, created new test world then opened the world and then exited the game.

**Comment by mcenderdragon** [comment]
this is a note for me: https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/actuallyaddition/AtomicReconstructor.java I have to do it like there

**Comment by jesmores** [comment]
Thanks, if you need someone to test a build I'd be happy to :)

**Comment by mcenderdragon** [comment]
Could you try out this version:  [26.3.25](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.25)

**Comment by jesmores** [comment]
Nice, I'll try it out when I get home today.

**Comment by jesmores** [comment]
Nope, still doesn't work - same issue as before, `No such member: futurepack`. I replaced the FP jar from my last test pack with the new one you linked. :(

`/ct dumpzs` also doesn't list `futurepack` as an installed module.

**Comment by mcenderdragon** [comment]
have also tried `mods.futurepack` ? maybe it is there ?

**Comment by jesmores** [comment]
Yeah, I tried both, neither worked. Does it work locally for you? Maybe you sent me the wrong version of the jar.

**Comment by mcenderdragon** [comment]
no I cant test it, as I havent setup a proper crafttweaker.

**Comment by mcenderdragon** [comment]
Second attempt: [26.3.32](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.32) does this work ? ` mods.futurepack` and then something like `crushing.add(item, Item)`

edit fixed wrong version...

**Comment by jesmores** [comment]
Still doesn't work, but there's some progress. futurepack module now shows up in `/ct dumpzs` but it's not seeing the functions add/remove for each submodule. Just a getter method. Here's the latest.log that shows the errors when I try to use crushing and industrial recipe tweaks:

https://gist.github.com/jesmores/d783ac59fbc1180c3c44fd94a7e5abc5

Relevant part of the log:

    [22:12:06] [Server thread/INFO]: Saving and pausing game...
    [22:12:06] [Server thread/INFO]: Saving chunks for level 'TEST'/overworld
    [22:12:07] [main/INFO]: [CHAT] ERROR: test.zs:1 > No such static member in mods.futurepack: industrial
    [22:12:07] [main/INFO]: [CHAT] ERROR: test.zs:1 > Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.data.IData
    [22:12:07] [main/INFO]: [CHAT] ERROR: test.zs:2 > No such static member in mods.futurepack: crushing
    [22:12:07] [main/INFO]: [CHAT] ERROR: test.zs:2 > Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.data.IData
    [22:12:07] [main/INFO]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: test.zs}: Bad type on operand stack\nException Details:\n  Location:\n    Test.__script__()V @54: invokestatic\n  Reason:\n    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to '[Lcrafttweaker/api/data/IData;'\n  Current Frame:\n    bci: @54\n    flags: { }\n    locals: { }\n    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }\n  Bytecode:\n    0x0000000: 0112 0abd 000c 5912 0d12 0f12 0db8 0015\n    0x0000010: 59c7 0008 5701 a700 06b8 001b 5359 121c\n    0x0000020: 121c bd00 1e59 120d 0153 59c7 0008 5701\n    0x0000030: a700 06b8 0023 b800 2959 c700 0857 01a7\n    0x0000040: 0006 b800 2353 b900 2d02 0057 0112 0abd\n    0x0000050: 000c 5912 0d12 2f12 0db8 0015 59c7 0008\n    0x0000060: 5701 a700 06b8 001b 5359 121c 121c bd00\n    0x0000070: 1e59 120d 0153 59c7 0008 5701 a700 06b8\n    0x0000080: 0023 b800 2959 c700 0857 01a7 0006 b800\n    0x0000090: 2353 b900 2d02 0057 b1                 \n  Stackmap Table:\n    full_frame(@25,{},{Null,Object[#49],Object[#49],Integer,Object[#51]})\n    full_frame(@28,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@51,{},{Null,Object[#49],Object[#49],Integer,Object[#53]})\n    full_frame(@54,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@66,{},{Null,Object[#49],Object[#49],Integer,Object[#30]})\n    full_frame(@69,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@101,{},{Null,Object[#49],Object[#49],Integer,Object[#51]})\n    full_frame(@104,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@127,{},{Null,Object[#49],Object[#49],Integer,Object[#53]})\n    full_frame(@130,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@142,{},{Null,Object[#49],Object[#49],Integer,Object[#30]})\n    full_frame(@145,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n
    [22:12:07] [Server thread/INFO]: Saving chunks for level 'TEST'/the_nether

My test script:

    mods.futurepack.industrial.add(<minecraft:cobblestone>, [<minecraft:stonebrick>]);
    mods.futurepack.crushing.add(<minecraft:clay>, [<minecraft:hardened_clay>]);

**Comment by mcenderdragon** [comment]
ok it seams like crafttweaker has removed the auto matic registering of subtypes. Lets try the next version ^^ [26.3.33](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.33)

**Comment by jesmores** [comment]
Bit more progress with that one. I see the `add` and `remove` functions on dumpzs, but they're parented to a `null` module instead of going under the `mods.futurepack` module.

Here's the relevant part from the log:

```
[08:57:46] [Server thread/INFO]: Saving chunks for level 'TEST'/overworld
[08:57:46] [main/INFO]: [CHAT] ERROR: system:  is already defined in that package
[08:57:46] [main/INFO]: [CHAT] ERROR: system:  is already defined in that package
[08:57:46] [main/INFO]: [CHAT] ERROR: system:  is already defined in that package
[08:57:46] [main/INFO]: [CHAT] ERROR: system:  is already defined in that package
[08:57:46] [main/INFO]: [CHAT] ERROR: system:  is already defined in that package
[08:57:46] [main/INFO]: [CHAT] ERROR: test.zs:1 > No such static member in mods.futurepack: industrial
[08:57:46] [main/INFO]: [CHAT] ERROR: test.zs:1 > Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.data.IData
[08:57:46] [main/INFO]: [CHAT] ERROR: test.zs:2 > No such static member in mods.futurepack: crushing
[08:57:46] [main/INFO]: [CHAT] ERROR: test.zs:2 > Cannot cast ZenTypeNative: crafttweaker.item.IItemStack to ZenTypeNative: crafttweaker.data.IData
[08:57:46] [main/INFO]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: test.zs}: Bad type on operand stack\nException Details:\n  Location:\n    Test.__script__()V @54: invokestatic\n  Reason:\n    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to '[Lcrafttweaker/api/data/IData;'\n  Current Frame:\n    bci: @54\n    flags: { }\n    locals: { }\n    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }\n  Bytecode:\n    0x0000000: 0112 0abd 000c 5912 0d12 0f12 0db8 0015\n    0x0000010: 59c7 0008 5701 a700 06b8 001b 5359 121c\n    0x0000020: 121c bd00 1e59 120d 0153 59c7 0008 5701\n    0x0000030: a700 06b8 0023 b800 2959 c700 0857 01a7\n    0x0000040: 0006 b800 2353 b900 2d02 0057 0112 0abd\n    0x0000050: 000c 5912 0d12 2f12 0db8 0015 59c7 0008\n    0x0000060: 5701 a700 06b8 001b 5359 121c 121c bd00\n    0x0000070: 1e59 120d 0153 59c7 0008 5701 a700 06b8\n    0x0000080: 0023 b800 2959 c700 0857 01a7 0006 b800\n    0x0000090: 2353 b900 2d02 0057 b1                 \n  Stackmap Table:\n    full_frame(@25,{},{Null,Object[#49],Object[#49],Integer,Object[#51]})\n    full_frame(@28,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@51,{},{Null,Object[#49],Object[#49],Integer,Object[#53]})\n    full_frame(@54,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@66,{},{Null,Object[#49],Object[#49],Integer,Object[#30]})\n    full_frame(@69,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@101,{},{Null,Object[#49],Object[#49],Integer,Object[#51]})\n    full_frame(@104,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@127,{},{Null,Object[#49],Object[#49],Integer,Object[#53]})\n    full_frame(@130,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n    full_frame(@142,{},{Null,Object[#49],Object[#49],Integer,Object[#30]})\n    full_frame(@145,{},{Null,Object[#49],Object[#49],Integer,Object[#12]})\n
```

**Comment by mcenderdragon** [comment]
wow this version of crafttweaker is realy dump, the old one worked so fine -.-

**Comment by mcenderdragon** [comment]
so lets see if it now works... [26.3.36](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.36)

**Comment by jesmores** [comment]
More progress! The modules all show up in `/ct dumpzs` output now, with their correct add and remove functions. Still doesn't work though.

Logs: https://gist.github.com/jesmores/9db2ee3ad93f4913ab1d900840fab16b

Script
```
mods.futurepack.industrial.add(<minecraft:cobblestone>, [<minecraft:stonebrick>]);
mods.futurepack.crushing.add(<minecraft:clay>, <minecraft:hardened_clay>);
```

Relevant logs
```
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: java.lang.ClassNotFoundException: minetweaker.api.minecraft.MineTweakerMC
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.Class.forName0(Native Method)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.Class.forName(Class.java:260)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.ClassRegistry.getItem(ClassRegistry.java:28)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:22)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:51)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:36)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at Test.__script__(test.zs:1)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at __ZenMain__.run(Test)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:147)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:54)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:113)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:46)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:02:37] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: java.lang.ClassNotFoundException: minetweaker.api.minecraft.MineTweakerMC
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.Class.forName0(Native Method)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.Class.forName(Class.java:260)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.ClassRegistry.getItem(ClassRegistry.java:28)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:26)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:51)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at futurepack.extensions.minetweaker.implementation.IndustrialBridge.add(IndustrialBridge.java:36)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at Test.__script__(test.zs:1)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at __ZenMain__.run(Test)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:147)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:54)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:113)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:46)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:02:37] [main/INFO]: [futurepack.extensions.minetweaker.ClassRegistry:getItem:33]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

```
[08:03:12] [Server thread/INFO]: jtjin joined the game
[08:03:13] [main/INFO]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: test.zs}: null
[08:03:13] [Server thread/INFO]: Saving and pausing game...
```

**Comment by mcenderdragon** [comment]
hopefully: [26.3.42](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.42)

**Comment by jesmores** [comment]
That did it! It works now :D  

![image](https://user-images.githubusercontent.com/125214/34091122-821b4d00-e370-11e7-9b7f-b27c973d9b40.png)

Thanks!
