### ISSUE TITLE
Futurepack-1.12.1-26.2.27 and Futurepack-1.12.1-26.2.39 forge 2544 MC 1-12-2 Crashes

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#311]
Crashes are game breaking/world breaking. Why forge 2544? Because they've fixed some memory leak issues that were in recent previous versions.

First crash Futurepack-1.12.1-26.2.27

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]} as it does not exist in BlockStateContainer{block=fp:neon_sand, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at futurepack.common.block.BlockWire$4.isValidBlock(BlockWire.java:213)
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:242)
	at futurepack.common.block.BlockWire.func_189540_a(BlockWire.java:245)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at net.minecraft.world.World.func_175685_c(World.java:491)
	at net.minecraft.world.World.func_175722_b(World.java:439)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at futurepack.common.block.BlockWirelessRedstoneReceiver.updateReceiversAround(BlockWirelessRedstoneReceiver.java:78)
	at futurepack.common.block.BlockWirelessRedstoneTransmitter.updateState(BlockWirelessRedstoneTransmitter.java:65)
	at futurepack.common.block.BlockWirelessRedstoneTransmitter.func_180650_b(BlockWirelessRedstoneTransmitter.java:49)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:736)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:753)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Full crash log and futurepack log
[crash-2017-11-17_18.15.44-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/1484180/crash-2017-11-17_18.15.44-server.txt)

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1484181/FP-Latest.log)

Crash after updating to Futurepack-1.12.1-26.2.39

java.lang.RuntimeException: class futurepack.common.block.TileEntityDungeonCore is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78)
	at net.minecraft.tileentity.TileEntity.func_189517_E_(TileEntity.java:205)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:255)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:753)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

Full crash log

[crash-2017-11-17_18.55.59-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/1484182/crash-2017-11-17_18.55.59-server.txt)

**Comment by mcenderdragon** [comment]
Ok the first crash "java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]} as it does not exist in BlockStateContainer{block=fp:neon_sand, properties=[type]}" should not happen at all, this only can happen if something is modifing the world from different threads, and this should not happen, it is very weird.

And the second on is just me derping, I have literlay notes saing I shoul not forget adding the tile mapping... consider it as fixed :)

**Comment by mcenderdragon** [comment]
Fixed: [Version 26.2.41](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.41)

**Comment by trogarus** [comment]
You're human, we derp, don't worry bout it =) Look, it's an amazing mod. You are keeping it working and smashing out bugs as quickly as you can. You're one of the very active devs that really take care of their mod and their players. You're entitled to a derp here and there. Don't hold yourself to standards of perfection. As a flawed human being (which we all are), perfection is far outside the scope of our being.

I'll grab the files now and slot them in next restart. Playing the game now and clearing out areas for my base, in each dimension =) Gotta luv the rf builder for that once you have the materials to make one, and the energy infrastructure to support it =) Thanks again for all your work on a thoroughly enjoyable mod.

**Comment by mcenderdragon** [comment]
It is really cool to have such a nice and comfortable community :D

**Comment by trogarus** [comment]
Yeah, well, beware, not all the "community" is always so fine and comfortable. Hopefully it stays that way for the ones you interact with here, but I've been around a few years and have seen things. Hopefully said things will not befall you in the way community interacts with you =)
