### ISSUE TITLE
[Sponge][World Generation] Crashes

### ISSUE THREAD

**Issue by Mordna** [mcenderdragon/Futurepack-API#372]
Sometimes when a dungeon is generated it will produce an error with spongeforge. (Runaway phase)
It also happens if the mod is used alone.
Stack trace: https://gist.github.com/Mordna/bd983f8ae314d56a1253900d2dbe8b3a

Using:
SpongeForge : 1.12.2-2586-7.1.0-BETA-2890
Minecraft : 1.12.2
Futurepack: 26.3.88 (for 1.12.2)

**Comment by mcenderdragon** [comment]
Wow, sponge is still this buggy ?

**Comment by mcenderdragon** [comment]
It seems like they somehow implemented the addSheduledTask wrong, I can only provide full support for Forge because spongeforge is such a huge bug, but I am glad they did manage to no longer crash custom dimensions but still world generation is buggy and produced chunk edges.

**Comment by mcenderdragon** [comment]
I did a workaround so at least you can use spongeforge until they fixed it: [26.3.140](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.140)

**Comment by Mordna** [comment]
The workaround is working, but there is a new error with sponge:
[Stacktrace](https://gist.github.com/Mordna/c02e65a4db911d150361930593cf3e4a)
I did not test it without spongeforge but it did not exist before that version of FP.

**Comment by mcenderdragon** [comment]
ok thats a new issue :) , I will look into it.

**Comment by Mordna** [comment]
It happened again using version 26.3.152 on a new world.
I only changed the spawn rate of both tech dungeons to 0.1
Stacktrace:
```
[10:39:51] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.api.util.PositionOutOfBoundsException: Position is out of bounds: expected in range (48, 0, 288) to (15, 0, 431) but got (48, 0, 288)
        at org.spongepowered.common.util.gen.AbstractBiomeBuffer.checkRange(AbstractBiomeBuffer.java:58) ~[AbstractBiomeBuffer.class:1.12.2-2611-7.1.0-BETA-2953]
        at org.spongepowered.common.util.gen.ObjectArrayMutableBiomeBuffer.setBiome(ObjectArrayMutableBiomeBuffer.java:105) ~[ObjectArrayMutableBiomeBuffer.class:1.12.2-2611-7.1.0-BETA-2953]
        at net.minecraft.world.biome.BiomeProvider.generateBiomes(BiomeProvider.java:558) ~[anl.class:?]
        at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:152) ~[SpongeChunkGeneratorForge.class:1.12.2-2611-7.1.0-BETA-2953]
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982) ~[axw.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
        at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3602) ~[MinecraftServer.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:815) ~[WorldManager.class:1.12.2-2611-7.1.0-BETA-2953]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760) ~[WorldManager.class:1.12.2-2611-7.1.0-BETA-2953]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3552) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
This line is interesting: Position is out of bounds: expected in range (48, 0, 288) to (15, 0, 431) but got (48, 0, 288)

Why is (48, 0, 288) not in the range since it is the start point? 

Also:
```
[10:39:44] [Dungeon Spawner/ERROR] [Sponge]: /* Expected to exit phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                          */
[10:39:44] [Dungeon Spawner/ERROR] [Sponge]: /* But instead found phase: GenerationPhase{}{PopulatorGenerationPhaseState:POPULATOR_RUNNING} 
```

Found that it happens mostly using forge 2624 - so it should be an issue of spongeforge, but the recommended version is working fine (the error is appearing very sparse)

**Comment by Mordna** [comment]
I am closing the world generation issue since it is working (only the last error is happening, but nothing with threading anymore)
