### ISSUE TITLE
Server crash on chunk pregen -IllegalArgumentException: Cannot get property PropertyInteger

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#386]
https://paste.fedoraproject.org/paste/oQerqQoAgA63rrsRm8okpg

```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]} as it does not exist in BlockStateContainer{block=fp:neon_sand, properties=[type]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at futurepack.common.block.BlockWire$4.isValidBlock(BlockWire.java:213)
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:242)
	at futurepack.common.block.BlockWire.func_189540_a(BlockWire.java:245)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at net.minecraft.world.World.func_175685_c(World.java:491)
	at net.minecraft.world.World.func_175722_b(World.java:439)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at futurepack.common.block.BlockWirelessRedstoneReceiver.updateReceiversAround(BlockWirelessRedstoneReceiver.java:78)
	at futurepack.common.block.BlockWirelessRedstoneTransmitter.updateState(BlockWirelessRedstoneTransmitter.java:65)
	at futurepack.common.block.BlockWirelessRedstoneTransmitter.func_180650_b(BlockWirelessRedstoneTransmitter.java:49)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:736)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcenderdragon** [comment]
Yet another in theorie not happenable crash ^TM

**Comment by ProsperCraft** [comment]
I went to the location, and I see the problem perhaps, overlapping worldgen from your own mod.

![2018-02-18_11 25 26](https://user-images.githubusercontent.com/4427684/36355317-8b9c4334-149e-11e8-9758-3c60acc4b5d0.png)
![2018-02-18_11 25 29](https://user-images.githubusercontent.com/4427684/36355318-8d6e800a-149e-11e8-9108-78758fcf2f85.png)
![2018-02-18_11 25 36](https://user-images.githubusercontent.com/4427684/36355319-8f042aaa-149e-11e8-9944-fb34431b1933.png)

The block location is the ADSPT in that screenshot.

**Comment by ProsperCraft** [comment]
![2018-02-18_11 27 55](https://user-images.githubusercontent.com/4427684/36355334-cac2bf5c-149e-11e8-8762-f7beef181cf2.png)

**Comment by mcenderdragon** [comment]
the dungeons get generated last, so I guess pre gen uses multiply threads.

**Comment by Speiger** [comment]
@mcenderdragon no as soon you throw in Multithreaded Generation the game breaks the second the first chunk is generated. The only multithreaded parts are those who are already multithreaded in the core game.
This is more 2 structures coliding with each other.
Edit: Also the Crashlog shows that the error has nothing todo with the pregenerator.

**Comment by ProsperCraft** [comment]
It might be important here to let you know I turned down the frequency of the dungeons quite a bit - 
https://gist.github.com/ProsperCraft/ccbfa6c2b3436b778326210d2b6ff9a4

And ^ Speiger is the Pregen mod author.

**Comment by Speiger** [comment]
to throw a bit more information out the code for the generation in Chunk Pregenerator can be compared to forges version, https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/server/command/ChunkGenWorker.java#L134     
The only difference is that i take more care about memory cleanup then all the other options.

**Comment by mcenderdragon** [comment]
This should fix this issues,a dn the other worlgen issues [26.3.118](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.118)

**Comment by ProsperCraft** [comment]
Awesome, pushing to curse?

**Comment by mcenderdragon** [comment]
Well over the night alot of issues popped up, so I will at first make sure all the crashes are fixed, but yeh There are alot of fixes that needs pushing.

**Comment by mcenderdragon** [comment]
I pushed the 118 to curse :)
