### ISSUE TITLE
Curse Feedback: mod compatiblity

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#478]
> 
> Fantastic mod, though cross-capability with other mods is pretty poor compared to the other big name mods. Can't craft some Futurepack items (that use the standard crafting table); most noteably the techtable/part press on a tinker's construct crafting station. And the recipes for Futurepack don't use the basic shapeless item lists recipes that most mods use. Two good examples are recipes involving chests or sticks. You can only use vanilla 'oak' chests which can be problematic when using Quark (who doesn't use quark?) which adds variants of each wood chests.  And some mods have variants of sticks (such as the Betweenlands with it's Weedwood sticks). Having the recipes use the universal stick list for seamless crafting would do a lot to enable mod cross capability and improve the odds of people adding this mod to a modpack. 
>

- [x] OreDict in crafting
- [x] crafting in modtables not possible (yes this is VERY hard)

**Comment by mcenderdragon** [comment]
The recipe fixes: [26.3.90](https://redsnake-games.de/Downloads/fp/fp.php?t=P6g2o.bszqztAVbLzqvI8A--)

**Comment by Convergence2738** [comment]
It crashed during the load. 
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Full crashlog:

(Can't upload the full crashlog for some reason). 

Just swapped out the Futurepack versions.

**Comment by Convergence2738** [comment]
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at futurepack.common.crafting.ShapedOreRecipeWithResearch.checkIngredient(ShapedOreRecipeWithResearch.java:82)
	at futurepack.common.crafting.ShapelessOreRecipeWithResearch$$Lambda$1728/986249383.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at futurepack.common.crafting.ShapelessOreRecipeWithResearch.<init>(ShapelessOreRecipeWithResearch.java:50)
	at futurepack.common.crafting.ShapelessOreRecipeWithResearch$Factory.parse(ShapelessOreRecipeWithResearch.java:98)
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409)
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711)
	at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$1711/954874494.apply(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668)
	at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$1709/1768366410.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2437995472 bytes (2325 MB) / 6442450944 bytes (6144 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2740 Optifine OptiFine_1.12.2_HD_U_E1 128 mods loaded, 128 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructe

**Comment by mcenderdragon** [comment]
dammit scala.arrays!!!!

Edit: fix is coming.

**Comment by mcenderdragon** [comment]
[26.3.291](https://redsnake-games.de/Downloads/fp/fp.php?t=n1Tluzb3TJQ9dNYmGE0EOg--)

**Comment by Convergence2738** [comment]
it loaded! So I'll go through the recipes and see how it looks. nvm: It's glorious. yeah, this is awesome. You should release this officially soon. I can see the iron sticks on the ore list. Techtable still is using the oak chest, you can use <ore:chestWood> for wooden chests. That is the commonly used chest ore list.

I see a few new adds to the tech tree ;) I'll take a look. Feels like technology mixed with Thaumcraft with the researching. It's quite amazing. I'm shocked I never found this mod until now.

**Comment by Convergence2738** [comment]
[Futurepack Furnacecoke.txt](https://github.com/mcenderdragon/Futurepack-API/files/2263467/Futurepack.Furnacecoke.txt)

Here is my code script for the industrial furnace recipes. It's recipes for using coal coke from other mods. It's mainly the industrial furnace with a few sample on the neon variant (the neon is largely a straight upgrade tot he standard furnace anyways and they don't use coal much).

**Comment by mcenderdragon** [comment]
ok techtable is fixed.

**Comment by Convergence2738** [comment]
Found a bug with the update. It's the scala arrays again, though bug is different.

Bug is a CTD on scan from the E-Scanner. I was in a big tech dungeon and accidently scanned a purple metal block and it procced the crash.
[crash-2018-08-07_15.18.40-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/2268240/crash-2018-08-07_15.18.40-client.txt)

Futurepack-1.12.2-26.3.291

**Comment by Convergence2738** [comment]
yeah, double checked the CTD reason, it seems to be connected to the dungeon block protection. outside the dungeon it works fine, but scanning a block inside the dungeon makes a CTD proc.

**Comment by mcenderdragon** [comment]
Fixed: [26.3.293](https://redsnake-games.de/Downloads/fp/fp.php?t=4aZUDN71dyICfYQlXlDM_w--)

**Comment by mcenderdragon** [comment]
@Convergence2738  Please try this version: [26.3.300](https://redsnake-games.de/Downloads/fp/fp.php?t=o0Wwr2eDJM1OkFvw5J144Q--) alot of other mod crafting tables should be now supported.

**Comment by Convergence2738** [comment]
Sweet, I'll give it a go through. I'll note any bugs as I go.
