### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#483]
https://hastebin.com/zuhideyuka.md

**Comment by mcenderdragon** [comment]
es war was mit the ingredient manager, der bei wugand immer abstürtzt.

**Comment by mcenderdragon** [comment]
```
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ConcurrentModificationException
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.research.TagDictReplacer.replaceResearchPredicates(TagDictReplacer.java:88)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.research.TagDictReplacer.checkResearches(TagDictReplacer.java:51)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.research.TagDictReplacer.access$000(TagDictReplacer.java:18)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.research.TagDictReplacer$1.run(TagDictReplacer.java:37)
[16:50:52] [FP-Research Ingredient Replacer/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
```
