### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#506]
```
java.lang.NullPointerException: Exception in server tick loop
	at java.util.HashSet.add(Unknown Source)
	at futurepack.common.dim.atmosphere.AtmosphereManager.addWorldToUpdateQuee(AtmosphereManager.java:289)
	at futurepack.common.dim.atmosphere.AtmosphereManager.onWorldTick(AtmosphereManager.java:280)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_838_AtmosphereManager_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

```

FP: 26.3.417

**Comment by mcenderdragon** [comment]
[Version 26.3.449](https://redsnake-games.de/Downloads/fp/fp.php?t=Wz48IUyLc0M3BMPYYX7OVQ--)
