### ISSUE TITLE
Batteries break on discharge

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#512]
see: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2644868-futurepack-mod-discover-new-dimensions?page=25#c494

> 
> 
> Having a rather weird bug where after shift-clicking batteries into the battery box (which puts them into [+] and [-] first slots instead of main battery storage slots) the battery that gets into the [-] gets its energy storage basically erased, it turns into Whatever Battery 0/0 and is impossible to charge or fix anymore.
> 
> Any ideas?

https://media-minecraftforum.cursecdn.com/attachments/290/199/636775417088805817.png

**Comment by mcenderdragon** [comment]
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> ForgelinPlugin (Forgelin-1.7.4.jar)
> Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
> AstralCore (astralsorcery-1.12.2-1.9.4.jar)
> AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-108-universal.jar)
> LoadingPlugin (Quark-r1.5-130.jar)
> Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
> CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
> Contact their authors BEFORE contacting forge
> 
> // Don't do that.
> 
> Time: 11/12/18 9:07 PM
> Description: Manually triggered debug crash
> 
> java.lang.Throwable
> at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1924)
> at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
> at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> at net.minecraft.client.main.Main.main(SourceFile:123)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1924)
> 
> -- Affected level --
> Details:
> Level name: MpServer
> All players: 1 total; [EntityPlayerSP['Zarvera'/276, l='MpServer', x=2035.48, y=82.00, z=879.29]]
> Chunk stats: MultiplayerChunkCache: 1089, 1089
> Level seed: 0
> Level generator: ID 10 - quark_realistic, ver 0. Features enabled: false
> Level generator options:
> Level spawn location: World: (1232,64,1248), Chunk: (at 0,4,0 in 77,78; contains blocks 1232,0,1248 to 1247,255,1263), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
> Level time: 7462929 game time, 5536148 day time
> Level dimension: 0
> Level storage version: 0x00000 - Unknown?
> Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Forced entities: 65 total; [EntityMinecartChest['Minecart with Chest'/387, l='MpServer', x=2076.70, y=47.00, z=866.08], EntityLlama['Llama'/1035, l='MpServer', x=2038.74, y=78.00, z=814.10], EntityLlama['Llama'/270, l='MpServer', x=1992.41, y=88.00, z=848.50], EntityCow['Cow'/911, l='MpServer', x=1976.81, y=72.00, z=841.71], EntityIYHaster['Haster'/1684, l='MpServer', x=2073.50, y=86.00, z=868.50], EntityPlayerSP['Zarvera'/276, l='MpServer', x=2035.48, y=82.00, z=879.29], EntityIYHaster['Haster'/1685, l='MpServer', x=2073.50, y=86.00, z=871.50], EntityChicken['Chicken'/409, l='MpServer', x=1966.91, y=73.00, z=857.72], EntityLlama['Llama'/921, l='MpServer', x=1956.34, y=88.00, z=819.10], EntityChicken['Chicken'/410, l='MpServer', x=1967.11, y=73.00, z=856.50], EntityIYBlubber['Blubber'/2202, l='MpServer', x=2000.50, y=106.00, z=844.50], EntityCow['Cow'/411, l='MpServer', x=1963.23, y=71.00, z=862.45], EntityLlama['Llama'/801, l='MpServer', x=2106.41, y=97.00, z=891.10], EntityLlama['Llama'/546, l='MpServer', x=2032.89, y=119.00, z=939.30], EntitySkeleton['Skeleton'/1960, l='MpServer', x=2079.50, y=96.00, z=803.50], EntityDonkey['Donkey'/556, l='MpServer', x=1981.15, y=87.00, z=943.00], EntityLlama['Llama'/814, l='MpServer', x=2006.91, y=78.00, z=824.51], EntityLlama['Llama'/815, l='MpServer', x=2009.55, y=78.00, z=824.50], EntityLlama['Llama'/816, l='MpServer', x=2008.47, y=94.00, z=830.58], EntityLlama['Llama'/817, l='MpServer', x=2014.69, y=81.00, z=829.44], EntityIYSonicBoomCreeper['Sonic Boom Creeper'/435, l='MpServer', x=2052.50, y=102.00, z=884.17], EntityZombie['Zombie'/1975, l='MpServer', x=2011.50, y=50.00, z=857.50], EntityLlama['Llama'/953, l='MpServer', x=2029.64, y=79.00, z=801.91], EntityLlama['Llama'/575, l='MpServer', x=2004.57, y=98.00, z=836.48], EntityLlama['Llama'/576, l='MpServer', x=2005.58, y=96.00, z=834.90], EntityLlama['Llama'/577, l='MpServer', x=2013.64, y=109.00, z=845.90], EntityLlama['Llama'/450, l='MpServer', x=2016.90, y=118.00, z=940.40], EntityDonkey['Donkey'/707, l='MpServer', x=1969.05, y=91.00, z=945.12], EntityLlama['Llama'/454, l='MpServer', x=2067.91, y=78.00, z=834.67], EntityIYGremlin['Gremlin Girl'/2503, l='MpServer', x=2079.50, y=85.00, z=840.66], EntityIYSonicBoomCreeper['Sonic Boom Creeper'/2381, l='MpServer', x=2044.50, y=78.00, z=933.50], EntityIYSonicBoomCreeper['Sonic Boom Creeper'/2382, l='MpServer', x=2046.50, y=78.00, z=933.50], EntityIYLeaper['Leaper'/2388, l='MpServer', x=2033.51, y=76.00, z=937.43], EntityLlama['Llama'/855, l='MpServer', x=1994.45, y=83.00, z=830.50], EntityLlama['Llama'/599, l='MpServer', x=2107.55, y=90.00, z=850.45], EntityCreeper['Creeper'/2392, l='MpServer', x=1978.50, y=76.00, z=911.50], EntityLlama['Llama'/473, l='MpServer', x=2023.56, y=110.00, z=853.55], EntityLlama['Llama'/987, l='MpServer', x=2097.55, y=102.00, z=809.42], EntityLlama['Llama'/988, l='MpServer', x=2111.89, y=100.00, z=809.50], EntityItem['item.item.awakenedvoidorb'/477, l='MpServer', x=2025.50, y=77.94, z=862.50], EntityLlama['Llama'/989, l='MpServer', x=2109.50, y=104.00, z=803.51], EntityCow['Cow'/863, l='MpServer', x=1984.51, y=81.00, z=836.80], EntityLlama['Llama'/1121, l='MpServer', x=2041.91, y=75.00, z=825.47], EntityCow['Cow'/354, l='MpServer', x=1975.84, y=72.00, z=863.32], EntityLlama['Llama'/1122, l='MpServer', x=2038.52, y=76.00, z=823.90], EntityLlama['Llama'/359, l='MpServer', x=2018.01, y=107.00, z=842.46], EntityLlama['Llama'/487, l='MpServer', x=2027.50, y=78.00, z=828.09], EntityLlama['Llama'/488, l='MpServer', x=2020.88, y=79.00, z=817.91], EntityLlama['Llama'/489, l='MpServer', x=2029.36, y=78.00, z=830.52], EntityCreeper['Creeper'/1897, l='MpServer', x=2063.50, y=74.00, z=928.50], EntityCreeper['Creeper'/1898, l='MpServer', x=2063.50, y=74.00, z=929.50], EntityCreeper['Creeper'/364, l='MpServer', x=2010.54, y=75.00, z=896.52], EntityIYAmanjak['Amanjak'/1900, l='MpServer', x=2062.50, y=74.00, z=927.50], EntityLlama['Llama'/1007, l='MpServer', x=2038.52, y=77.00, z=807.42], EntityLlama['Llama'/1008, l='MpServer', x=2041.64, y=77.00, z=809.01], EntityLlama['Llama'/1137, l='MpServer', x=2040.08, y=121.00, z=953.26], EntityDonkey['Donkey'/759, l='MpServer', x=1987.98, y=86.00, z=949.13], EntityLlama['Llama'/760, l='MpServer', x=2094.66, y=100.00, z=800.63], EntityIYDividerArm['Divider Arm'/2552, l='MpServer', x=2047.50, y=121.00, z=928.50], EntityDonkey['Donkey'/506, l='MpServer', x=1996.01, y=88.00, z=938.57], EntityIYDivider['Divider'/634, l='MpServer', x=2076.69, y=53.00, z=839.59], EntityDonkey['Donkey'/507, l='MpServer', x=1995.30, y=87.00, z=941.30], EntityDonkey['Donkey'/508, l='MpServer', x=1993.98, y=88.00, z=939.00], EntityDonkey['Donkey'/509, l='MpServer', x=1996.57, y=89.00, z=929.17], EntityCreeper['Creeper'/1791, l='MpServer', x=1967.50, y=72.00, z=912.50]]
> Retry entities: 0 total; []
> Server brand: fml,forge
> Server type: Integrated singleplayer server
> Stacktrace:
> at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
> at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
> at net.minecraft.client.main.Main.main(SourceFile:123)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.12.2
> Operating System: Windows 7 (amd64) version 6.1
> Java Version: 1.8.0_191, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 2065487576 bytes (1969 MB) / 3548381184 bytes (3384 MB) up to 5726797824 bytes (5461 MB)
> JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6144m
> IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> FML: MCP 9.42 Powered by Forge 14.23.5.2772 92 mods loaded, 92 mods active
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> | State | ID | Version | Source | Signature |
> |:--------- |:-------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
> | UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None |
> | UCHIJAAAA | mcp | 9.42 | minecraft.jar | None |
> | UCHIJAAAA | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2772-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | UCHIJAAAA | forge | 14.23.5.2772 | forge-1.12.2-14.23.5.2772-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | UCHIJAAAA | advancedrocketrycore | 1 | minecraft.jar | None |
> | UCHIJAAAA | foamfixcore | 7.7.4 | minecraft.jar | None |
> | UCHIJAAAA | libvulpes | 0.2.8.-39 | LibVulpes-1.12.2-0.2.8-39-universal.jar | None |
> | UCHIJAAAA | advancedrocketry | 1.4.1.-108 | AdvancedRocketry-1.12.2-1.4.1-108-universal.jar | None |
> | UCHIJAAAA | aether_legacy | 1.12.2-v3.2 | aether_legacy-1.12.2-v3.2.jar | None |
> | UCHIJAAAA | mcjtylib_ng | 3.0.6 | mcjtylib-1.12-3.0.6.jar | None |
> | UCHIJAAAA | hologui | 0.0.3-beta | hologui-1.12-0.0.3-beta.jar | None |
> | UCHIJAAAA | ariente | 0.0.4-alpha | ariente-1.12-0.0.4-alpha.jar | None |
> | UCHIJAAAA | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None |
> | UCHIJAAAA | fp | 26.3.417 | Futurepack-1.12.2-26.3.417.jar | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
> | UCHIJAAAA | crafttweaker | 4.1.11 | CraftTweaker2-1.12-4.1.11.jar | None |
> | UCHIJAAAA | astralsorcery | 1.9.4 | astralsorcery-1.12.2-1.9.4.jar | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
> | UCHIJAAAA | quark | r1.5-130 | Quark-r1.5-130.jar | None |
> | UCHIJAAAA | autoreglib | 1.3-20 | AutoRegLib-1.3-20.jar | None |
> | UCHIJAAAA | badmobs | 1.1.27 | BadMobs-1.12.2-1.1.27.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
> | UCHIJAAAA | betterbuilderswands | 0.12.0 | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None |
> | UCHIJAAAA | bookshelf | 2.3.567 | Bookshelf-1.12.2-2.3.567.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
> | UCHIJAAAA | brytemod | 1.0.0 | brytemod-1.0.jar | None |
> | UCHIJAAAA | mcmultipart | 2.5.3 | MCMultiPart-2.5.3.jar | None |
> | UCHIJAAAA | redstoneflux | 2.1.0 | RedstoneFlux-1.12-2.1.0.6-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> | UCHIJAAAA | sonarcore | 5.0.16 | sonarcore-1.12.2-5.0.16-16.jar | None |
> | UCHIJAAAA | calculator | 5.0.9 | calculator-1.12.2-5.0.9-9.jar | None |
> | UCHIJAAAA | clockworkphase2 | 1.12-0.1.5 | clockworkphase2-1.12-0.1.5.jar | None |
> | UCHIJAAAA | ctgui | 1.0.0 | CraftTweaker2-1.12-4.1.11.jar | None |
> | UCHIJAAAA | mtlib | 3.0.5 | MTLib-3.0.5.jar | None |
> | UCHIJAAAA | modtweaker | 4.0.15 | modtweaker-4.0.15.jar | None |
> | UCHIJAAAA | jei | 4.12.1.217 | jei_1.12.2-4.12.1.217.jar | None |
> | UCHIJAAAA | crafttweakerjei | 2.0.2 | CraftTweaker2-1.12-4.1.11.jar | None |
> | UCHIJAAAA | ctm | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar | None |
> | UCHIJAAAA | cyclopscore | 0.11.10 | CyclopsCore-1.12.2-0.11.10.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> | UCHIJAAAA | dbag | 1.12.2-4.0 | dbag-4.0.jar | None |
> | UCHIJAAAA | diethopper | 1.1 | diethopper-1.1.jar | None |
> | UCHIJAAAA | drawbridges | 0.1 | Drawbridges-1.0.1.jar | None |
> | UCHIJAAAA | dungeonmobs | 5.5.1 | dungeonmobs-5.5.1-MC1.12.2.jar | None |
> | UCHIJAAAA | ebwizardry | 4.1.2 | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar | None |
> | UCHIJAAAA | eplus | 5.0.173 | EnchantingPlus-1.12.2-5.0.173.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
> | UCHIJAAAA | enchdesc | 1.1.12 | EnchantmentDescriptions-1.12.2-1.1.12.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
> | UCHIJAAAA | endercompass | 1.2.6.2 | EnderCompass-1.12-1.2.6.2.jar | None |
> | UCHIJAAAA | evilcraft | 0.10.63 | EvilCraft-1.12.2-0.10.63.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> | UCHIJAAAA | evilcraftcompat | 1.0.0 | EvilCraft-1.12.2-0.10.63.jar | None |
> | UCHIJAAAA | externaltweaker | 0.3 | externaltweaker-1.12-0.3.jar | None |
> | UCHIJAAAA | fastleafdecay | v14 | FastLeafDecay-v14.jar | None |
> | UCHIJAAAA | finite-water-control | 1.0 | finite-water-control-1.12-1.0.jar | None |
> | UCHIJAAAA | foamfix | 0.10.2-1.12.2 | foamfix-0.10.2-1.12.2.jar | None |
> | UCHIJAAAA | forgelin | 1.7.4 | Forgelin-1.7.4.jar | None |
> | UCHIJAAAA | fp.api | 1.1.0 | Futurepack-1.12.2-26.3.417.jar | None |
> | UCHIJAAAA | waila | 1.8.26 | Hwyla-1.8.26-B41_1.12.2.jar | None |
> | UCHIJAAAA | mantle | 1.12-1.3.3.39 | Mantle-1.12-1.3.3.39.jar | None |
> | UCHIJAAAA | inspirations | 1.12.2-0.2.3 | Inspirations-1.12.2-0.2.3.jar | None |
> | UCHIJAAAA | iymts_mob_mod | 0.2.0 | iymts_mob_mod_1.12.2-2611-ver.0.2.0.jar | None |
> | UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar | None |
> | UCHIJAAAA | jeresources | 0.8.9.48 | JustEnoughResources-1.12.2-0.8.9.48.jar | None |
> | UCHIJAAAA | magneticraft | 2.5.2 | Magneticraft_1.12-2.5.2-dev.jar | None |
> | UCHIJAAAA | manawell | 0.0.2 | manawell-1.12--0.0.2.jar | None |
> | UCHIJAAAA | matteroverdrive | 0.6.2.0 | MatterOverdrive-1.12.2-0.6.2.0-universal.jar | None |
> | UCHIJAAAA | metalworks | 1.5.0 | Metalworks-1.5.0.jar | None |
> | UCHIJAAAA | minestrapp | 5.4.0A | Minestrappolation+5.5.0.jar | None |
> | UCHIJAAAA | modelloader | 1.1.5 | modelloader-1.1.5.jar | None |
> | UCHIJAAAA | naturescompass | 1.5.1 | NaturesCompass-1.12.2-1.5.1.jar | None |
> | UCHIJAAAA | nomobbat | 1.1 | NoBat-1.12.2-frg14.23.3.2655.jar | None |
> | UCHIJAAAA | nmsot | 1.2.2-mc1.12.2 | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar | None |
> | UCHIJAAAA | recipehandler | 0.12 | NoMoreRecipeConflict-0.12(1.12.2).jar | None |
> | UCHIJAAAA | norecipebook | 1.2.1 | noRecipeBook_v1.2.2formc1.12.2.jar | None |
> | UCHIJAAAA | placebo | 1.5.0 | Placebo-1.12.2-1.5.0.jar | None |
> | UCHIJAAAA | practicallogistics2 | 3.0.4 | practicallogistics2-1.12.2-3.0.4.jar | None |
> | UCHIJAAAA | rv | 0.0.31 | RavenousVoid-0.0.31.jar | None |
> | UCHIJAAAA | refinedstorage | 1.6.9 | refinedstorage-1.6.9.jar | None |
> | UCHIJAAAA | rustic | 1.0.12 | rustic-1.0.12.jar | None |
> | UCHIJAAAA | cardboardboxes | 0.0.2.7 | SBM-CardboardBoxes-1.12.2-0.0.2b7.jar | None |
> | UCHIJAAAA | t3s4ebw | 1.0 | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar | None |
> | UCHIJAAAA | shadowmc | 3.8.0 | ShadowMC-1.12-3.8.0.jar | None |
> | UCHIJAAAA | solar | 1.0.3 | Solar-1.0.3.jar | None |
> | UCHIJAAAA | stg | 1.12.2-1.2.3 | stg-1.12.2-1.2.3.jar | None |
> | UCHIJAAAA | tammodized | 0.15.5 | TamModized-1.12.1-0.15.5.jar | None |
> | UCHIJAAAA | tesla | 1.0.63 | Tesla-1.12.2-1.0.63.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
> | UCHIJAAAA | toroquest | 1.12.2-5.2 | toroquest-1.12.2-5.2.jar | None |
> | UCHIJAAAA | trumpetskeleton | 1.12-1.0.2.1 | trumpetskeleton-1.12-1.0.2.1.jar | None |
> | UCHIJAAAA | underwaterutilities | @VERSION@ | UnderwaterUtilities-1.12-1.3.3.jar | None |
> | UCHIJAAAA | of | 0.11 | Useful+Interior+-+0.11+[1.12.2].jar | None |
> | UCHIJAAAA | voidcraft | 0.26.10 | VoidCraft-1.12-0.26.10.jar | None |
> | UCHIJAAAA | wailaharvestability | 1.1.12 | WailaHarvestability-mc1.12-1.1.12.jar | None |
> | UCHIJAAAA | waterworks | 1.12.2-1.0.12 | Waterworks-1.12.2-1.0.12.jar | None |
> | UCHIJAAAA | witherskelefix | 2.6.1 | Wither+Skeleton+Tweaks-1.12.2-2.6.1.jar | None |
> | UCHIJAAAA | worleycaves | 1.3.0 | worleycaves-1.3.0.jar | None |
> | UCHIJAAAA | wts | 1.1.0 | WTS-1.1.0.jar | None |
> | UCHIJAAAA | arcaneworld | 0.0.8 | arcaneworld-1.12.2-0.0.8.jar | None |
> | UCHIJAAAA | kiwi | 0.2.4.2 | Kiwi-1.12.2-0.2.4.2.jar | None |
> | UCHIJAAAA | cuisine | 0.3.1-build568 | Cuisine-0.3.1-build568.jar | None |
> 
> Loaded coremods (and transformers):
> ForgelinPlugin (Forgelin-1.7.4.jar)
> 
> Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
> com.chocohead.biab.BornInABarn
> AstralCore (astralsorcery-1.12.2-1.9.4.jar)
> 
> AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-108-universal.jar)
> zmaster587.advancedRocketry.asm.ClassTransformer
> LoadingPlugin (Quark-r1.5-130.jar)
> vazkii.quark.base.asm.ClassTransformer
> Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
> pl.asie.foamfix.coremod.FoamFixTransformer
> CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
> team.chisel.ctm.client.asm.CTMTransformer
> GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 411.63' Renderer: 'GeForce GTX 760/PCIe/SSE2'
> Pulsar/inspirations loaded Pulses:
> - InspirationsShared (Enabled/Forced)
> - InspirationsBuilding (Enabled/Not Forced)
> - InspirationsUtility (Enabled/Not Forced)
> - InspirationsTools (Enabled/Not Forced)
> - InspirationsRecipes (Enabled/Not Forced)
> - InspirationsTweaks (Enabled/Not Forced)
> - InspirationsShared (Enabled/Forced)
> - WailaPlugin (Enabled/Not Forced)
> 
> Launched Version: MultiMC5
> LWJGL: 2.9.4
> OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.6.0 NVIDIA 411.63, NVIDIA Corporation
> GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> Using VBOs: Yes
> Is Modded: Definitely; Client brand changed to 'fml,forge'
> Type: Client (map_client.txt)
> Resource Packs: AudioCraftV1.5.zip
> Current Language: English (US)
> Profiler Position: N/A (disabled)
> CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

**Comment by mcenderdragon** [comment]
This was not reproduce able in tests, it is connected to some other mod.

**Comment by mcenderdragon** [comment]
> I was not able to reproduce it at all either even on the same instance.
> My only thought - are batteries connected to research mechanic in a way Flash Servers are? As in "you can't use this yet"? Some dungeons don't generate Forcefield that needs Key 1 or 2 making it possible to walk around until for instance Key 3 is required without needing 1 or 2, so maybe grabbing unresearched yet battery can cause this? The only batteries i've broken this way are Large Battery and Neon Batteries that i've hauled from a Dungeon early on. I've tried all kinds of things with crafted ones and those pulled from creative tab and they behave properly.

**Comment by mcenderdragon** [comment]
so maybe wrong/no NBT tag in dungeins
