### ISSUE TITLE
Deep Core can crash the game

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#513]
> java.lang.ClassCastException: futurepack.common.block.TileEntityWire cannot be cast to futurepack.common.block.TileEntityBedrockRift
>     at futurepack.common.block.multiblock.DeepCoreLogic.getRift(DeepCoreLogic.java:310)
>     at futurepack.common.block.multiblock.DeepCoreLogic.getRift(DeepCoreLogic.java:36)
>     at futurepack.api.interfaces.IDeepCoreLogic.isRiftReady(IDeepCoreLogic.java:29)
>     at futurepack.common.block.multiblock.DeepCoreLogic.isWorking(DeepCoreLogic.java:95)
>     at futurepack.common.block.multiblock.TileEntityDeepCoreMinerMain.isWorking(TileEntityDeepCoreMinerMain.java:152)
>     at futurepack.common.block.TileEntityModificationBase.calcMinHeat(TileEntityModificationBase.java:515)
>     at futurepack.common.block.TileEntityModificationBase.func_73660_a(TileEntityModificationBase.java:270)
>     at net.minecraft.world.World.func_72939_s(World.java:1835)
>     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
>     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
>     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Thread.java:745)

Reported by stebel Ivan#8810 on discord.

**Comment by mcenderdragon** [comment]
Solved: [26.3.463](https://redsnake-games.de/Downloads/fp/fp.php?t=qm5Cu12jeAe3srrN9GkODg--)
