### ISSUE TITLE
Sanitise in-world ship teleport

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#529]
if this is not done, it crahses

```
java.lang.IllegalArgumentException: Try to teleprt outside of World borders!
	at futurepack.common.spaceships.FPSpaceShipSelector.moveShip(FPSpaceShipSelector.java:732)
	at futurepack.common.block.TileEntityBoardComputer.jump(TileEntityBoardComputer.java:610)
	at futurepack.common.block.TileEntityBoardComputer.func_73660_a(TileEntityBoardComputer.java:109)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ProsperCraft** [comment]
Years later this had returned - 

Players are trying to fly their FP ship to a distant location in the Middle Earth, which is the Lord Of the Rings mod dim, there are no world borders in any of our worlds.

Modpack - https://www.curseforge.com/minecraft/modpacks/towncraft
1.16.5
Futurepack-1.16.4-31.1.8226

Crash- 
https://gist.github.com/ProsperCraft/14aab2d7df9b07450239cf83f09885a4
Debug log-
https://gist.githubusercontent.com/ProsperCraft/b3701e22a3e8802204a1637a28c50e7b/raw/250ca20081a20e9a0c91c42c7bb81e6dd9672b4a/gistfile1.txt
