### ISSUE TITLE
Crash when teleporting enderIO blocks

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#530]
Crashreport: https://pastebin.com/sxc3nD2w.

Happened when a Ship antempted to warp to menelaus.

```
java.lang.RuntimeException: Cannot create a TileEntity for a block that doesn't have a TileEntity. This is not a problem with EnderCore, this is caused by the caller.
        at com.enderio.core.common.BlockEnder.createTileEntity(BlockEnder.java:67)
        at futurepack.common.spaceships.SaveBlockMover.copie(SaveBlockMover.java:122)
        at futurepack.common.spaceships.FPSpaceShipSelector.transferShips(FPSpaceShipSelector.java:383)
        at futurepack.common.block.TileEntityBoardComputer.jump(TileEntityBoardComputer.java:653)
        at futurepack.common.block.TileEntityBoardComputer.func_73660_a(TileEntityBoardComputer.java:109)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcenderdragon** [comment]
SOlved in 26.3.474
