### ISSUE TITLE
[26.4.7] Server

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#536]
- [x] Support cable do not light when tranfering SP
- [x] Flash server needs to be output when transfering SP
- [x] Deep core does not accept SP

**Comment by mcenderdragon** [comment]
- sometimes the cables glow though. (Only not glwoign when output from flash server ?)

**Comment by mcenderdragon** [comment]
- [x] Deep core nimmt SP an wenn si direkt kommen, aber nicht über kabel.

**Comment by mcenderdragon** [comment]
---- [ ] Centrifuge does not accept SP--- no its the Flashserver

**Comment by mcenderdragon** [comment]
- [x] Flashserver funktioniert im mutltiplayer garnicht mehr.

**Comment by mcenderdragon** [comment]
- [x] Crash when scanning neon pipe:
```
18:22:25] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
```

**Comment by mcenderdragon** [comment]
- [x] Hexler geht nicht. (weil @Wugand mal auf die ganzen dinge eingehen soll die ich geschrieben habe)
