### ISSUE TITLE
RF to NE crash while jumping to menelaus

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#543]
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at futurepack.common.block.TileEntityRFtoNEConverter.hasCapability(TileEntityRFtoNEConverter.java:171)
	at sonar.core.handlers.energy.tiles.TileHandlerForge.canRenderConnection(TileHandlerForge.java:24)
	at sonar.core.handlers.energy.tiles.TileHandlerForge.canAddEnergy(TileHandlerForge.java:29)
	at sonar.core.handlers.energy.EnergyTransferHandler.getTileHandler(EnergyTransferHandler.java:95)
	at sonar.flux.connection.transfer.handlers.ConnectionTransferHandler.setTransfer(ConnectionTransferHandler.java:127)
	at sonar.flux.connection.transfer.handlers.ConnectionTransferHandler.updateTransfers(ConnectionTransferHandler.java:145)
	at sonar.flux.common.tileentity.TileFlux.updateTransfers(TileFlux.java:88)
	at sonar.flux.common.tileentity.TileFluxConnector.updateTransfers(TileFluxConnector.java:42)
	at sonar.flux.common.tileentity.energy.TileAbstractEnergyConnector.onNeighborChange(TileAbstractEnergyConnector.java:28)
	at sonar.flux.common.block.FluxSidedConnection.updateTransfers(FluxSidedConnection.java:40)
	at sonar.flux.common.block.FluxSidedConnection.onNeighborChange(FluxSidedConnection.java:27)
	at net.minecraft.world.World.func_175666_e(World.java:3811)
	at net.minecraft.world.World.func_175713_t(World.java:2486)
	at net.minecraft.block.BlockContainer.func_180663_b(SourceFile:48)
	at futurepack.common.block.BlockHoldingTile.func_180663_b(BlockHoldingTile.java:48)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175698_g(World.java:398)
	at futurepack.common.spaceships.SaveBlockMover.delete(SaveBlockMover.java:193)
	at futurepack.common.spaceships.FPSpaceShipSelector.transferShips(FPSpaceShipSelector.java:384)
	at futurepack.common.block.TileEntityBoardComputer.jump(TileEntityBoardComputer.java:600)
	at futurepack.common.block.TileEntityBoardComputer.func_73660_a(TileEntityBoardComputer.java:135)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcenderdragon** [comment]
solved in [26.4.27](https://redsnake-games.de/Downloads/fp/fp.php?t=gQQWuQcUYTuZeMSw4sFfkQ--)
