### ISSUE TITLE
Crash While Loading (no other mod installed)

### ISSUE THREAD

**Issue by RozyZx** [mcenderdragon/Futurepack-API#546]
[crash-2019-02-13_09.33.04-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/2858614/crash-2019-02-13_09.33.04-client.txt)

---- Minecraft Crash Report ----
// My bad.

Time: 2/13/19 9:33 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Futurepack (fp)
Caused by: java.lang.NullPointerException
	at futurepack.api.resources.AssetsDownloader.registerResource(AssetsDownloader.java:88)
	at futurepack.api.resources.AssetsDownloader.registerResources(AssetsDownloader.java:122)
	at futurepack.api.resources.FuturepackDefaultResources.registerFuturepackDefaults(FuturepackDefaultResources.java:92)
	at futurepack.api.resources.FuturepackDefaultResources.downloadFuturepackRersources(FuturepackDefaultResources.java:44)
	at futurepack.common.ProxyClient.preInit(ProxyClient.java:79)
	at futurepack.common.FPMain.preInit(FPMain.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105678720 bytes (100 MB) / 347320320 bytes (331 MB) up to 1664352256 bytes (1587 MB)
	JVM Flags: 6 total; -Xmx1600M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2811 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2811.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2811 | forge-1.12.2-14.23.5.2811.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCE   | fp        | 26.4.42      | Futurepack-1.12.2-26.4.42.jar | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| LC    | fp.api    | 1.1.0        | Futurepack-1.12.2-26.4.42.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 418.81' Renderer: 'GeForce 930MX/PCIe/SSE2'

**Comment by RozyZx** [comment]
I got the crash right after changing the config of OTHER mod and relaunch the game. The game run with no problem before (as far as i remember it was run on 2811 too, maybe it was 'my' error). I'd tried to run fp with my backup game, which is using forge 2796, and its working now.

**Comment by mcenderdragon** [comment]
I did not know it could crash there, I will dig into this...

**Comment by mcenderdragon** [comment]
Do you use a special launcher or any special setup (so non vanilla laucnher) ?

**Comment by RozyZx** [comment]
i'm using titan launcher tho.... guess its time to do it the right way. Thanks for digging it up.

**Comment by mcenderdragon** [comment]
I am asking because files in ´´.minecraft/assets´´ had files with not all data they should have and thus it crashed.

**Comment by RozyZx** [comment]
o yea,, i tried to launch the mod with 2811 again, it worked fine now. I have no idea what had happened to my game.
For the record, i tried with forge 2814, it worked fine too.. Thanks

**Comment by mcenderdragon** [comment]
The problem was an broken assets file so nothing forge or minecraft direktly related, I wonder why it broke in the first place

**Comment by RozyZx** [comment]
I wonder why that happened too... I 'think' I didn't change anything beside the config file before it occur.... Well, at least now I know why it broke... sorry for wasting ur time tho... thanks

**Comment by mitchngwen** [comment]
How do you fix the broken asset file?

**Comment by RozyZx** [comment]
Relaunch minecraft with the mod while online, so it will redownload any broken or missing asset... i think
