### ISSUE TITLE
BlockPusher break

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#549]
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-03-01 23:07:39 CST
Description: Exception in server tick loop

java.lang.NullPointerException
    at futurepack.common.block.BlockPusher.breakBlock(BlockPusher.java:26)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:608)
    at net.minecraft.world.World.setBlockState(World.java:509)
    at net.minecraft.world.World.setBlockToAir(World.java:565)
    at futurepack.common.dim.ChunkProviderMenelaus.genHoles(ChunkProviderMenelaus.java:143)
    at futurepack.common.dim.ChunkProviderMenelaus.populate(ChunkProviderMenelaus.java:124)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1162)
    at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1141)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:166)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:422)
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:388)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows Server 2008 R2 (amd64) version 6.1
  Java Version: 1.8.0_171, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 239758488 bytes (228 MB) / 1132462080 bytes (1080 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 4 total; -XX:+UseG1GC -XX:+AggressiveOpts -XX:+UseCompressedOops -Xmx4G
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  CraftBukkit Information: Running: CatServer version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) true
                              Plugins: {}
                              Warnings: DEFAULT
                              Reload Count: 0
                              Threads: { RUNNABLE Attach Listener: [], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:93)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:92)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51), net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30), java.lang.Thread.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Thread-4: [java.io.FileOutputStream.writeBytes(Native Method), java.io.FileOutputStream.write(Unknown Source), java.io.BufferedOutputStream.flushBuffer(Unknown Source), java.io.BufferedOutputStream.flush(Unknown Source), java.io.PrintStream.write(Unknown Source), java.io.PrintStream.write(Unknown Source), org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82), java.io.FilterOutputStream.write(Unknown Source), java.io.PrintStream.write(Unknown Source), java.io.FilterOutputStream.write(Unknown Source), org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:40), java.lang.Thread.run(Unknown Source)], WAITING AE Compass Service: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], RUNNABLE Signal Dispatcher: [], TIMED_WAITING ResearchIOThread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING World Simulation Thread: [java.lang.Thread.sleep(Native Method), CoroUtil.world.WorldDirector.run(WorldDirector.java:429), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214), jline.WindowsTerminal.access$000(WindowsTerminal.java:54), jline.WindowsTerminal$1.read(WindowsTerminal.java:156), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243), jline.internal.InputStreamReader.read(InputStreamReader.java:257), jline.internal.InputStreamReader.read(InputStreamReader.java:194), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126), jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211), jline.console.ConsoleReader.readLine(ConsoleReader.java:2460), jline.console.ConsoleReader.readLine(ConsoleReader.java:2372), net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:120)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Boden Frost: [java.lang.Thread.sleep(Native Method), futurepack.common.dim.ProviderEnvia.run(ProviderEnvia.java:264), java.lang.Thread.run(Unknown Source)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275), java.lang.Thread.run(Unknown Source)], WAITING ic2-poolthread-1: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), ic2.core.util.PriorityExecutor$FixedPriorityQueue.take(PriorityExecutor.java:143), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
                              Recent tasks from -31--1{}
  FML: MCP 9.42 Powered by Forge 14.23.5.2815 55 mods loaded, 55 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                     | Version       | Source                                                   | Signature                                |
       |:------ |:---------------------- |:------------- |:-------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft              | 1.12.2        | minecraft.jar                                            | None                                     |
       | LCHIJA | mcp                    | 9.42          | minecraft.jar                                            | None                                     |
       | LCHIJA | FML                    | 8.0.99.99     | CatServer-f02dfc5.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                  | 14.23.5.2815  | CatServer-f02dfc5.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | opencomputers|core     | 1.7.4.153     | minecraft.jar                                            | None                                     |
       | LCHIJA | foamfixcore            | 7.7.4         | minecraft.jar                                            | None                                     |
       | LCHIJA | dsurroundcore          |               | minecraft.jar                                            | None                                     |
       | LCHIJA | autoreglib             | 1.3-26        | [P][魔法科高中的劣等生前置]AutoRegLib-1.3-26.jar                    | None                                     |
       | LCHIJA | psi                    | r1.1-71       | [P][魔法科高中的劣等生]Psi-r1.1-71.jar                            | None                                     |
       | LCHIJA | mysticalmechanics      | 0.5           | [S][余烬前置]Mystical+Mechanics-0.5.jar                      | None                                     |
       | LCHIJA | embers                 | 1.12          | [S][余烬]EmbersRekindled-1.12.jar                          | None                                     |
       | LCHIJA | bookshelf              | 2.3.574       | [S][前置]Bookshelf-1.12.2-2.3.574.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | codechickenlib         | 3.2.2.353     | [S][前置]CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | extendedrenderer       | v1.0          | [S][前置]CoroUtil-1.12.1-1.2.27.jar                        | None                                     |
       | LCHIJA | coroutil               | 1.12.1-1.2.27 | [S][前置]CoroUtil-1.12.1-1.2.27.jar                        | None                                     |
       | LCHIJA | configmod              | v1.0          | [S][前置]CoroUtil-1.12.1-1.2.27.jar                        | None                                     |
       | LCHIJA | forgelin               | 1.8.2         | [S][前置]Forgelin-1.8.2.jar                                | None                                     |
       | LCHIJA | refraction             | 1.9           | [S][折射]refraction-1.12.2-1.9.10.jar                      | None                                     |
       | LCHIJA | librarianlib           | 4.15          | [S][前置]librarianlib-1.12.2-4.15.jar                      | None                                     |
       | LCHIJA | mcmultipart            | 2.5.3         | [S][前置]MCMultiPart-2.5.3.jar                             | None                                     |
       | LCHIJA | redstoneflux           | 2.1.0         | [S][前置]RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | ic2                    | 2.8.111-ex112 | [S][工业2]industrialcraft-2-2.8.111-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | sonarcore              | 5.0.19        | [S][前置]sonarcore-1.12.2-5.0.19-20.jar                    | None                                     |
       | LCHIJA | rockhounding_core      | 3.16          | [S][地质探险]rockhounding_core-1.12.2-3.16.jar               | None                                     |
       | LCHIJA | gbook                  | 2.8.3         | [S][前置]Guidebook-1.12.2-2.8.3.jar                        | None                                     |
       | LCHIJA | rockhounding_chemistry | 1.12.2-3.29   | [S][地质探险_化学]rockhounding_chemistry-1.12.2-3.29.jar       | None                                     |
       | LCHIJA | rockhounding_surface   | 1.12.2-3.11   | [S][地质探险_地表]rockhounding_surface-1.12.2-3.11.jar         | None                                     |
       | LCHIJA | rockhounding_rocks     | 1.12.2-3.18   | [S][地质探险_岩石]rockhounding_rocks-1.12.2-3.18.jar           | None                                     |
       | LCHIJA | rockhounding_oretiers  | 1.12.2-3.07   | [S][地质探险_矿石]rockhounding_oretiers-1.12.2-3.07.jar        | None                                     |
       | LCHIJA | ftblib                 | 5.4.1.84      | [S][安全]FTBLib-5.4.1.84.jar                               | None                                     |
       | LCHIJA | ftbutilities           | 5.3.0.82      | [S][安全]FTBUtilities-5.3.0.82.jar                         | None                                     |
       | LCHIJA | vanillafix             | 1.0.9-97      | [S][崩溃修复]VanillaFix-1.0.9-97.jar                         | None                                     |
       | LCHIJA | factorytech            | 1.5           | [S][工厂技术]FactoryTech-1.6.6a.jar                          | None                                     |
       | LCHIJA | appliedenergistics2    | rv6-stable-6  | [S][应用能源]appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | opencomputers          | 1.7.4.153     | [S][开放式电脑]OpenComputers-MC1.12.2-1.7.4.153.jar           | None                                     |
       | LCHIJA | erebus                 | 1.0.25        | [S][昆虫世界]Erebus-1.0.25.jar                               | None                                     |
       | LCHIJA | baubles                | 1.5.2         | [S][饰品]Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCHIJA | fp                     | 26.4.44       | [S][飞向未来]Futurepack-1.12.2-26.4.44.jar                   | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
       | LCHIJA | crafttweaker           | 4.1.13        | [S][魔改]CraftTweaker2-1.12-4.1.13.jar                     | None                                     |
       | LCHIJA | astralsorcery          | 1.10.11       | [S][星辉魔法]astralsorcery-1.12.2-1.10.11.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | biomesoplenty          | 7.0.1.2425    | [S][更多生物群系]BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar | None                                     |
       | LCHIJA | vrgenerator            | 5.0.1         | [S][永光发电机]VisibleRayGenerator-1.12-5.0.1-universal.jar   | None                                     |
       | LCHIJA | foamfix                | 0.10.3-1.12.2 | [S][泡沫修复]foamfix-0.10.3-1.12.2.jar                       | None                                     |
       | LCHIJA | harvestcraft           | 1.12.2zb      | [S][潘马斯]Pam's+HarvestCraft+1.12.2zb.jar                  | None                                     |
       | LCHIJA | practicallogistics2    | 3.0.8         | [S][物流监控]practicallogistics2-1.12.2-3.0.8-11.jar         | None                                     |
       | LCHIJA | fp.api                 | 1.1.0         | [S][飞向未来]Futurepack-1.12.2-26.4.44.jar                   | None                                     |
       | LCHIJA | advanced_solar_panels  | 4.3.0         | [S][高级太阳能]Advanced+Solar+Panels-4.3.0.jar                | None                                     |
       | LCHIJA | grimoireofgaia         | 1.6.8         | [S][魔典盖亚]GrimoireOfGaia3-1.12.2-1.6.8.jar                | None                                     |
       | LCHIJA | crafttweakerjei        | 2.0.2         | [S][魔改]CraftTweaker2-1.12-4.1.13.jar                     | None                                     |
       | LCHIJA | mtrm                   | 1.2.2.30      | [S][魔改]MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
       | LCHIJA | mtlib                  | 3.0.5         | [S][魔改]MTLib-3.0.5.jar                                   | None                                     |
       | LCHIJA | modtweaker             | 4.0.15        | [S][魔改]modtweaker-4.0.15.jar                             | None                                     |
       | LCHIJA | thebetweenlands        | 3.4.4         | [S][交错次元]TheBetweenlands-3.4.4-server.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | dsurround              | 3.4.10.6      | [S][动态环绕]DynamicSurroundings-1.12.2-3.4.10.6.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | librarianliblate       | 4.15          | [S][前置]librarianlib-1.12.2-4.15.jar                      | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin ([S][前置]Forgelin-1.8.2.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.4-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      TransformerLoader ([S][开放式电脑]OpenComputers-MC1.12.2-1.7.4.153.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      VanillaFixLoadingPlugin ([S][崩溃修复]VanillaFix-1.0.9-97.jar)
                                        
                                      AstralCore ([S][星辉魔法]astralsorcery-1.12.2-1.10.11.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
                                        org.blockartistry.DynSurround.asm.Transformer
                                      LibrarianLib Plugin ([S][前置]librarianlib-1.12.2-4.15.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([S][泡沫修复]foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Futurepack API (fp.api)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 20; []
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
```

**Comment by mcenderdragon** [comment]
Original https://paste.ubuntu.com/p/D62kynmGyy/, from Metasequoia#5452

**Comment by mcenderdragon** [comment]
its a bukkit...
