### ISSUE TITLE
Client crash after breaking a composite chest. NPE

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#552]
I have a player that was breaking a "glichy Futurepack composite chest that looked normal and composite" and crashed with 
https://gist.github.com/ProsperCraft/344f21b8222e9044f3ea99006880d4e5
Then when he logs back in he gets this-
The chest was in a region that had been rolled back to two days prior.

https://gist.github.com/ProsperCraft/808873cc5a1bc95792f8aad51453de4f

https://gist.github.com/ProsperCraft/38f6b807cb8ec889f35da4c1bb18110f

https://gist.github.com/ProsperCraft/7a351a11c2fccd932aec9cd2be3d476a
https://gist.github.com/ProsperCraft/ebdd957c8c1f5ea363874eadf95e6680
https://gist.github.com/ProsperCraft/fd5e9174d4b4af9031c39613f1b3257e

**Comment by mcenderdragon** [comment]
There is hardly anything I can do about this as the crashes where it just writes `NullPointerException` are completly useless without the stracktrace and the other crash is hapening outside of futurepack code.
```
java.lang.NullPointerException
    at net.minecraft.client.renderer.tileentity.TileEntityChestRenderer.render(SourceFile:42)
    at net.minecraft.client.renderer.tileentity.TileEntityChestRenderer.render(SourceFile:15)
    at net.minecraftforge.client.ForgeHooksClient.renderTileItem(ForgeHooksClient.java:583)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.renderByItem(TileEntityItemStackRenderer.java:121)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.renderByItem(TileEntityItemStackRenderer.java:45)
    at reborncore.shields.client.RebornItemStackRenderer.renderByItem(RebornItemStackRenderer.java:116)
    at vswe.stevescarts.renders.ItemStackRenderer.renderByItem(ItemStackRenderer.java:25)
    at net.minecraft.client.renderer.RenderItem.renderItem(RenderItem.java:145)
    at codechicken.lib.render.item.CCRenderItem.renderItem(CCRenderItem.java:213)
    at net.minecraft.client.renderer.entity.RenderEntityItem.doRender(RenderEntityItem.java:138)
    at net.minecraft.client.renderer.entity.RenderEntityItem.doRender(RenderEntityItem.java:19)
    at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.doRender(WrappedEntityItemRenderer.java:33)
    at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.doRender(WrappedEntityItemRenderer.java:16)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:384)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:368)
    at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zbe000(RenderGlobal.java:2637)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:628)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1347)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

As this has not happened before and I have not changed anything regarding the chests kately have you updated/installed any new mods ?
