### ISSUE TITLE
Probably, you have seen this error, but maybe not? Yes, with composite chest and NPE.

### ISSUE THREAD

**Issue by MadRatSRP** [mcenderdragon/Futurepack-API#553]
[crash-2019-02-28_19.51.16-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955523/crash-2019-02-28_19.51.16-server.txt)
Probably these two are connected as well:
[crash-2019-03-07_09.24.09-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955526/crash-2019-03-07_09.24.09-server.txt)
[crash-2019-03-07_11.07.17-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955527/crash-2019-03-07_11.07.17-server.txt)
and these as well
[crash-2019-02-27_13.45.59-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955580/crash-2019-02-27_13.45.59-server.txt)
[crash-2019-02-27_13.46.00-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955581/crash-2019-02-27_13.46.00-server.txt)
[crash-2019-02-28_19.51.15-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955582/crash-2019-02-28_19.51.15-server.txt)
[crash-2019-02-27_12.26.38-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955583/crash-2019-02-27_12.26.38-server.txt)
[crash-2019-02-27_13.45.58-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2955584/crash-2019-02-27_13.45.58-server.txt)

**Comment by mcenderdragon** [comment]
All of them are completly new to me. Time so sort all of these crahes:
- _crash-2019-03-07_09.24.09-server.txt_: has nothing todo with futurepack the crash was inside vanilla at the entity `toroquest:toroquest_toro (net.torocraft.toroquest.entities.EntityToro)`
- _crash-2019-02-27_13.46.00-server.txt_ (same as _crash-2019-02-28_19.51.15-server.txt_, _crash-2019-02-27_13.45.59-server.txt_, _crash-2019-02-27_13.45.58-server.txt_, _crash-2019-02-28_19.51.15-server.txt_) interesting this could be the actual important crash
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at net.minecraft.inventory.ContainerChest.<init>(SourceFile:13)
    at futurepack.common.gui.FPGuiHandler.getServerGuiElement(FPGuiHandler.java:365)
    at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at futurepack.common.block.BlockCompositeChest.onBlockActivated(BlockCompositeChest.java:44)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```
- _crash-2019-03-07_11.07.17-server.txt_ random crash in vanilla about time from the a normal zombie
-  _crash-2019-02-27_12.26.38-server.txt_ this one is also interesting and different  
```
java.lang.NullPointerException
    at futurepack.common.dim.scanning.FPChunkScanner.lambda$onWorldUnload$0(FPChunkScanner.java:346)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at futurepack.common.dim.scanning.FPChunkScanner.onWorldUnload(FPChunkScanner.java:346)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3175_FPChunkScanner_onWorldUnload_Unload.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

Thank you for this amount of input, I hope it will help tracking down the bug.

**Comment by mcenderdragon** [comment]
About the composite crash: #552
Something in your world broke and that caused the tileEntity of the composite chest to disappear, these crashes are the result of the missing tileEntity. In Prosper craft someone said those chunk got restored? If so stop with that or change the tool, it does not restore the chunks fully. This crash also means the contents inside the chest are lost.

**Comment by MadRatSRP** [comment]
> All of them are completly new to me. Time so sort all of these crahes:
> 
> * _crash-2019-03-07_09.24.09-server.txt_: has nothing todo with futurepack the crash was inside vanilla at the entity `toroquest:toroquest_toro (net.torocraft.toroquest.entities.EntityToro)`
> * _crash-2019-02-27_13.46.00-server.txt_ (same as _crash-2019-02-28_19.51.15-server.txt_, _crash-2019-02-27_13.45.59-server.txt_, _crash-2019-02-27_13.45.58-server.txt_, _crash-2019-02-28_19.51.15-server.txt_) interesting this could be the actual important crash
> 
> ```
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
>     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>     at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>     at net.minecraft.util.Util.runTask(Util.java:531)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
>     at net.minecraft.inventory.ContainerChest.<init>(SourceFile:13)
>     at futurepack.common.gui.FPGuiHandler.getServerGuiElement(FPGuiHandler.java:365)
>     at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253)
>     at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
>     at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
>     at futurepack.common.block.BlockCompositeChest.onBlockActivated(BlockCompositeChest.java:44)
>     at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
>     at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
>     at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at net.minecraft.util.Util.runTask(Util.java:529)
>     ... 5 more
> ```
> * _crash-2019-03-07_11.07.17-server.txt_ random crash in vanilla about time from the a normal zombie
> * _crash-2019-02-27_12.26.38-server.txt_ this one is also interesting and different
> 
> ```
> java.lang.NullPointerException
>     at futurepack.common.dim.scanning.FPChunkScanner.lambda$onWorldUnload$0(FPChunkScanner.java:346)
>     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
>     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
>     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>     at futurepack.common.dim.scanning.FPChunkScanner.onWorldUnload(FPChunkScanner.java:346)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3175_FPChunkScanner_onWorldUnload_Unload.invoke(.dynamic)
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
>     at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Thread.java:748)
> ```
> Thank you for this amount of input, I hope it will help tracking down the bug.

Thank you as well, i reported first bug to the Toroquest team)
