### ISSUE TITLE
Crash in Chunk Scanner

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#554]
https://github.com/mcenderdragon/Futurepack-API/files/2955583/crash-2019-02-27_12.26.38-server.txt

```
java.lang.NullPointerException
    at futurepack.common.dim.scanning.FPChunkScanner.lambda$onWorldUnload$0(FPChunkScanner.java:346)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at futurepack.common.dim.scanning.FPChunkScanner.onWorldUnload(FPChunkScanner.java:346)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3175_FPChunkScanner_onWorldUnload_Unload.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:403)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

#553

**Comment by mcenderdragon** [comment]
https://openeye.openmods.info/crashes/787ef80b2a3e7e02bbb4b269576d68ab

**Comment by ProsperCraft** [comment]
Server crash - https://gist.github.com/ProsperCraft/e52309d9d889f380ff28d90fd128f1d5

Pack - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by mcenderdragon** [comment]
`buffer.stream().filter(b -> b.w == world).map(FPChunkScanner::saveRaw).forEach(b -> {`
this is the line is question, so somehow "b.w" is causing this. Why does buffer contain a null entry.
