### ISSUE TITLE
[Optifine] Error after loading world

### ISSUE THREAD

**Issue by kellixon** [mcenderdragon/Futurepack-API#568]
MC 1.12.2. Futurepack 26.4.75. Error immediately after loading world.
```
[13:22:22] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@5c9555bf:
java.lang.NullPointerException: null
	at futurepack.common.dim.protection.FPDungeonProtection.addChunkCaps(FPDungeonProtection.java:178) ~[FPDungeonProtection.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1500_FPDungeonProtection_addChunkCaps_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:685) [ForgeEventFactory.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:94) [axw.class:?]
	at net.optifine.util.ChunkUtils.findFieldHasEntities(ChunkUtils.java:58) [ChunkUtils.class:?]
	at net.optifine.util.ChunkUtils.<clinit>(ChunkUtils.java:22) [ChunkUtils.class:?]
	at net.minecraft.client.renderer.RenderGlobal.setupTerrain(RenderGlobal.java:1397) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1731) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:33:29] [Client thread/ERROR] [FML]: Index: 21 Listeners:
[14:33:29] [Client thread/ERROR] [FML]: 0: NORMAL
[14:33:29] [Client thread/ERROR] [FML]: 1: ASM: class thaumcraft.common.lib.events.PlayerEvents attachCapabilitiesPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 2: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@7c590c7e onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 3: ASM: class com.wuest.prefab.Events.ModEventHandler AttachItemStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 4: ASM: class techguns.capabilities.CapabilityEventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 5: ASM: class techguns.capabilities.CapabilityEventHandler attachCapabilitiesClient(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 6: ASM: class com.latmod.yabba.YabbaEventHandler attachWorldCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 7: ASM: com.minecolonies.coremod.event.EventHandler@60df99ae onAttachingCapabilitiesWorld(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 8: ASM: com.minecolonies.coremod.event.EventHandler@60df99ae onAttachingCapabilitiesChunk(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 9: ASM: baubles.common.event.EventHandlerEntity@64c5eaef attachCapabilitiesPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 10: ASM: ejektaflex.bountiful.proxy.ClientProxy@68d7a9ee attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 11: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@65c43003 onAttachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 12: ASM: mcjty.lib.McJtyLib$EventHandler@4b5488a5 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 13: ASM: mcjty.rftools.ForgeEventHandlers@6f272f99 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 14: ASM: mcjty.theoneprobe.ForgeEventHandlers@5b850574 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 15: ASM: blusunrize.immersiveengineering.common.util.compat.BaublesHelper@31568ad3 onCapabilitiesAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 16: ASM: increasemobs.capability.IncreaseMobsCapabilities@15087aaa onAttachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 17: ASM: com.buuz135.industrial.utils.compat.baubles.MeatFeederBauble$Event@6beae922 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 18: ASM: terrails.statskeeper.data.health.CapabilityHealth$Handler@325f191a attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 19: ASM: io.github.drmanganese.topaddons.config.capabilities.CapEvents@7a93ff13 onAttachCapabilityEntity(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 20: ASM: net.xalcon.torchmaster.common.EventHandlerServer@9c0f109 onWorldAttachCapabilityEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 21: ASM: futurepack.common.dim.protection.FPDungeonProtection@4c919783 addChunkCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 22: ASM: futurepack.common.dim.atmosphere.AtmosphereManager@6d6d8633 addAirCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 23: ASM: al132.alchemistry.EventHandler@7633fc37 onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 24: ASM: c4.comforts.common.capability.CapabilitySleepTime$EventHandler@8c2a173 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 25: ASM: c4.comforts.common.capability.CapabilitySleeping$EventHandler@56ec3be3 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 26: ASM: com.lothrazar.cyclicmagic.event.EventPlayerData@6b4c9508 onEntityConstruct(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 27: ASM: blusunrize.immersiveengineering.common.EventHandler@262d560c onCapabilitiesAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 28: ASM: com.kotori316.fluidtank.integration.ae2.AE2$@178815d attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 29: ASM: net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader@7644e17 tileEntity(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
[14:33:29] [Client thread/ERROR] [FML]: 30: LOWEST
[14:33:29] [Client thread/ERROR] [FML]: 31: ASM: baubles.common.event.EventHandlerItem@57b018e3 itemCapabilityAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
```

**Comment by mcenderdragon** [comment]
Ahh I see, Optifine is doing shit again... creating a chunk with a null world, great...

**Comment by mcenderdragon** [comment]
Please try if this version works: [26.4.76](https://redsnake-games.de/Downloads/fp/fp.php?t=DMypBl.0ROLTalCd7iKMzA--)

**Comment by kellixon** [comment]
No, also. Full log attached. Line 73192
[debug.zip](https://github.com/mcenderdragon/Futurepack-API/files/3179342/debug.zip)

**Comment by mcenderdragon** [comment]
Ahh this time the air caps crashed. Please try this version: [26.4.78](https://redsnake-games.de/Downloads/fp/fp.php?t=PCELWD7zRoEgDOkQ9ZcklQ--)

**Comment by kellixon** [comment]
Everything is fine (v.26.4.78), thanks for the quick fix!
