### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AjzaklijaStomaklija** [mcenderdragon/Futurepack-API#624]
A game crashed when i wanted to craft machineboard.I think the reason is because core is not showing core power and ram is not showing ram power.

https://pastebin.com/2Abicr87

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: mouseReleased event handler
	at futurepack.common.recipes.crafting.RecipeMaschin.func_77572_b(RecipeMaschin.java:33) ~[?:1.14.4-28.0.14] {re:classloading}
	at futurepack.common.recipes.crafting.RecipeMaschin.func_77572_b(RecipeMaschin.java:19) ~[?:1.14.4-28.0.14] {re:classloading}
	at futurepack.common.gui.inventory.GuiTechTable$ContainerTechTable.func_75130_a(GuiTechTable.java:414) ~[?:1.14.4-28.0.14] {re:classloading}
	at futurepack.common.gui.inventory.InventoryCraftingTechtable.func_70299_a(InventoryCraftingTechtable.java:48) ~[?:1.14.4-28.0.14] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:62) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:254) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:515) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:485) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at futurepack.common.gui.inventory.GuiTechTable.mouseReleased(GuiTechTable.java:241) ~[?:1.14.4-28.0.14] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3199/2056843526.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$2645/2010134328.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.platform.GLX.pollEvents(GLX.java:276) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:875) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.40.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$390/619929778.call(Unknown Source) [forge-1.14.4-28.1.40.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.0.0.jar:?] {}
```

I am saving this before pastebin deletes the rcashreport.
