### ISSUE TITLE
E-scanner bug on 1.14 server

### ISSUE THREAD

**Issue by K2uU3i** [mcenderdragon/Futurepack-API#625]
Scanning is fine but there is no GUI displayed for research progress and story. Only the text "data is loading" is showed but never really loads. Could this be the problem of the firewall on the server like some port should be opened,etc?
Below are some error infos on the server (might be irrelevant):

`[23:16:28] [Netty Epoll Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize futurepack.common.commands.DimensionArgument@2ac1922 (class futurepack.common.commands.DimensionArgument) - will not be sent to client!
[23:16:28] [Netty Epoll Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@52bf986f (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[23:16:28] [Netty Epoll Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@550cbac6 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[23:16:28] [Server thread/ERROR] [ne.mi.fm.ne.si.IndexedMessageCodec/SIMPLENET]: Received empty payload on channel fml:handshake`

**Comment by mcenderdragon** [comment]
I am using only the minecraft connection so when you joined the server the connection worked and all needed ports are open. "Data loading" means the packet with research data never gets to the client, hmmm...

**Comment by K2uU3i** [comment]
What kind of information can I provide to help you?

**Comment by mcenderdragon** [comment]
Please give me your forge version & installed mods.

**Comment by K2uU3i** [comment]
forge-1.14.4-28.2.0 and the only mod installed is futurepack

**Comment by mcenderdragon** [comment]
Seems like I broke the packet handling somewhere...

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: null
	at futurepack.common.research.ResearchManager.getById(ResearchManager.java:42) ~[?:1.14.4-28.0.23]
	at futurepack.client.research.LocalPlayerResearchHelper.setupData(LocalPlayerResearchHelper.java:34) ~[?:1.14.4-28.0.23]
	at futurepack.common.sync.MessageResearchResponse.consume(MessageResearchResponse.java:78) ~[?:1.14.4-28.0.23]
	at futurepack.common.sync.FPPacketHandler$$Lambda$4823/1423498776.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:124) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$5412/1406101130.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:124) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2029/500802478.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2031/97281693.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$5400/1446217799.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1783) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:55) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5458/443849416.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.1.jar:28.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/2142129482.call(Unknown Source) [forge-1.14.4-28.2.1.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
```

**Comment by K2uU3i** [comment]
patched in the version of 28.0.17?

**Comment by mcenderdragon** [comment]
no In 28.0.26

**Comment by mcenderdragon** [comment]
pushed to curseforge
