### ISSUE TITLE
[1.14.4-28.0.17] Industrial Furnace won't disappear/buggy

### ISSUE THREAD

**Issue by Kerbalino** [mcenderdragon/Futurepack-API#627]
In every world in which I placed down the Industrial Furnace, the block refuses to "disappear" out of the inventory and the block, when breaked, is actually still there with a collission and re-appears when the block is updated.

**Comment by mcenderdragon** [comment]
please provide your log.

**Comment by Kerbalino** [comment]
```
Error executing task on Client
java.lang.NullPointerException
	at nl.requios.effortlessbuilding.buildmodifier.UndoRedo.addUndo(UndoRedo.java:35)
	at nl.requios.effortlessbuilding.network.AddUndoMessage$Handler.lambda$handle$0(AddUndoMessage.java:75)
	at nl.requios.effortlessbuilding.network.AddUndoMessage$Handler$$Lambda$13645/1306013473.run(Unknown Source)
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
	at nl.requios.effortlessbuilding.network.AddUndoMessage$Handler.handle(AddUndoMessage.java:69)
	at nl.requios.effortlessbuilding.network.PacketHandler$$Lambda$9337/1365280387.accept(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:124)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$12687/1355375215.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:124)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79)
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2037/1014694927.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2039/1679102252.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74)
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$12656/1033295628.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1783)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:55)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$12938/285453504.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$398/891193852.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
```

There is a mod causing the bug to happen, but the strange thing is that it only happens with some machines, like the gas turbine.

**Comment by mcenderdragon** [comment]
This is a bug with effortless building, you should open an issue at their issue tracker: https://bitbucket.org/Requios/effortless-building/issues?status=new&status=open

**Comment by mcenderdragon** [comment]
Maybe linked to this: https://github.com/raoulvdberge/refinedstorage/issues/2449
