### ISSUE TITLE
[request] Quick patch for "/fp research reset"

### ISSUE THREAD

**Issue by DevTimur** [mcenderdragon/Futurepack-API#629]
Can you quickly patch command "**/fp research "_player_" reset**" so it acually work.
I want to make so player can wipe all researches by doing something special that run this command. But atm it just gives error.

So I ask you to make a small patch so this command just work. Thank you.

Version **Futurepack-1.12.2-26.4.89**, yes, it's **1.12.2** minecraft, my modpack in this version.

**Comment by mcenderdragon** [comment]
can you give me the server log? or latest + debug if on client.

**Comment by DevTimur** [comment]
Here you go.
<details>
  <summary>Error console text</summary>
  java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableCollection.clear(Unknown Source) ~[?:1.8.0_221]
	at futurepack.common.commands.CommandFuturepack.reset(CommandFuturepack.java:153) ~[CommandFuturepack.class:?]
	at futurepack.common.commands.CommandFuturepack.func_184881_a(CommandFuturepack.java:62) ~[CommandFuturepack.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
</details>

**Comment by DevTimur** [comment]
still no fix?

**Comment by mcenderdragon** [comment]
Not in 1.12 if I remember correctly, in 1.14 it should be fixed.

**Comment by DevTimur** [comment]
ok... but I asked specific for 1.12.2
> Version **Futurepack-1.12.2-26.4.89**, yes, it's **1.12.2** minecraft, my modpack in this version.

**Comment by SkyProgs** [comment]
We don't support 1.12.2 anymore. In newer versions it should be fixed.
