### ISSUE TITLE
Crash when removing core from machine

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#641]
```
java.lang.NullPointerException: Ticking block entity
	at futurepack.common.block.modification.InventoryModificationBase.getChipPower(InventoryModificationBase.java:249) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.getChipPower(TileEntityModificationBase.java:534) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.func_73660_a(TileEntityModificationBase.java:231) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```
```

java.lang.NullPointerException: Rendering screen
	at futurepack.common.block.modification.InventoryModificationBase.getCorePower(InventoryModificationBase.java:204) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.gui.inventory.GuiChipset.func_146976_a(GuiChipset.java:55) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:75) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at futurepack.common.gui.inventory.GuiChipset.render(GuiChipset.java:157) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:354) ~[?:?] {re:classloading}
```

**Comment by mcenderdragon** [comment]
When all part of machine are missing it crashed because PartsManager.joinUpdateable returns null.
```

if(parts.length==0)
	return null;
```
