### ISSUE TITLE
Crash in researcher GUI

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#642]
```
java.lang.NullPointerException: Rendering screen
	at futurepack.common.gui.inventory.GuiForscher.renderItems(GuiForscher.java:185) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.gui.inventory.GuiForscher.func_146976_a(GuiForscher.java:168) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:75) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at futurepack.common.gui.inventory.GuiForscher.render(GuiForscher.java:58) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:354) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$410/285781448.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}a
```
https://cdn.discordapp.com/attachments/501723564840321025/694072068131782716/crash-2020-03-30_08.28.42-clientResearchUpgrade2.txt
https://cdn.discordapp.com/attachments/501723564840321025/694072073324068915/crash-2020-03-30_08.33.49-clientResearcher_PlacedBackDown.txt

**Comment by mcenderdragon** [comment]
> Research for Science Upgrade tier 2 had 6 required resources
> the researcher has 4 slots
> i would have expected an out of bounds
> i have a nack for finding this shit sadly
> Opti bench and something else like this
> The Other thing
> Opti Bench
> The Other thing
> The Other thing
> Opti Bench
> Opti Bench
