### ISSUE TITLE
Crash when Monorail waypoints have no names

### ISSUE THREAD

**Issue by 88mmAufSfl8** [mcenderdragon/Futurepack-API#643]
Steps to the crash:
i placed down 2 Monorail Waypoints
i tried to rename those waypoints, wich doesn't work as of rn, i relaized this after i erased both of thier names
i placed down a Monorail Cart and interacted with it.
crashed
The world reverted to the last auto save.
further Info in the Log.
[crash-2020-03-30_14.08.07-serverMonoRailCart.txt](https://github.com/mcenderdragon/Futurepack-API/files/4402708/crash-2020-03-30_14.08.07-serverMonoRailCart.txt)
NOTE: The GUI of the Waypoint has no Texture, but this may be because of my texture pack.

**Comment by mcenderdragon** [comment]
```

java.lang.IndexOutOfBoundsException: Index: 69, Size: 69
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {}
	at net.minecraft.util.NonNullList.get(SourceFile:46) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_75142_b(Container.java:117) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at futurepack.common.gui.inventory.GuiMonocart$ContainerMonocart.func_75142_b(GuiMonocart.java:455) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:321) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerWorld$$Lambda$5274/582357502.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```
