### ISSUE TITLE
Ticking Entety Error With Gas Turbine 1.14.4

### ISSUE THREAD

**Issue by 88mmAufSfl8** [mcenderdragon/Futurepack-API#644]
I wanted to try to power a gas turbine generator with _**Steam**_ as it would count to me as a gas perhaps not burnable, yes, but still if a water turbine got hot enoutgh i would have worked in theory but as i was looking in the general direction of the turbine **GAS** with the energy configuration tool, wich i had changed to items on accident, it crashed
NOTE: Game Crashes when trying to loade the world in witch it occured.
[crash-2020-03-30_22.01.05-serverTheWaterSteamTurbineExperiemtn.txt](https://github.com/mcenderdragon/Futurepack-API/files/4405143/crash-2020-03-30_22.01.05-serverTheWaterSteamTurbineExperiemtn.txt)
_why do i have a nack for stuff like this?_

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: Ticking block entity
	at futurepack.common.block.modification.TileEntityFluidPump.pumpInFluid(TileEntityFluidPump.java:248) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.modification.TileEntityFluidPump.updateTile(TileEntityFluidPump.java:117) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.doUpdate(TileEntityModificationBase.java:432) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.func_73660_a(TileEntityModificationBase.java:270) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

```

**Comment by mcenderdragon** [comment]
Good jop, please continue doing what ever you do and find bugs :D

**Comment by mcenderdragon** [comment]
It was actually the fluid pump and not the turbine.

**Comment by 88mmAufSfl8** [comment]
i shall i shall
once you repair the support research module, as that will motivate me to contiune buidling up in my main world witch is now inaccesible because of it.

**Comment by mcenderdragon** [comment]
http://redsnake-games.de/Downloads/fp/fp.php?embed=vHWztik1kt_lgrz7LkMfhA-- this should let you play again.

**Comment by 88mmAufSfl8** [comment]
Ops
wrong issue

**Comment by 88mmAufSfl8** [comment]
Works now

**Comment by mcenderdragon** [comment]
nice
