### ISSUE TITLE
Unknown Crash when trying to craft upgraded Dungeon CPU's

### ISSUE THREAD

**Issue by 88mmAufSfl8** [mcenderdragon/Futurepack-API#645]
I wantet to try to make a water Steam Turbine COmbo again in a new world for witch i wanted the most powerful processor possible, i made 64 Dungeon Processors and when i wanted to upgrade them, it crashed. If they were requiered there were NO Support points
[crash-2020-03-30_22.28.50-serverDungeonProcessor Shenanigans.txt](https://github.com/mcenderdragon/Futurepack-API/files/4405376/crash-2020-03-30_22.28.50-serverDungeonProcessor.Shenanigans.txt)

On trying to rejoin the world, it loaded BUT as soon as i interacted with the assembler the game crashed with a tkiting tile entety exception.

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: Ticking block entity
	at futurepack.common.recipes.assembly.AssemblyDualRecipe.getOutput(AssemblyDualRecipe.java:48) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.inventory.TileEntityAssemblyTable.func_73660_a(TileEntityAssemblyTable.java:151) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```
