### ISSUE TITLE
Placing down the Support research module causes crash

### ISSUE THREAD

**Issue by 88mmAufSfl8** [mcenderdragon/Futurepack-API#646]
There was a research in the researcher "Redstone technologies", when i placed down the support Upgrade i immidetly crashed, and i fear that the world won't loade now.

[crash-2020-03-31_10.40.09-serverSupportResearchThing.txt](https://github.com/mcenderdragon/Futurepack-API/files/4407729/crash-2020-03-31_10.40.09-serverSupportResearchThing.txt)

my suspicions have confirmed themselfs and minecraft crashes, with the exit error being
"The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: futurepack.api.capabilities.CapabilitySupport cannot be cast to futurepack.api.capabilities.INeonEnergyStorage"

**Comment by mcenderdragon** [comment]
```
java.lang.ClassCastException: futurepack.api.capabilities.CapabilitySupport cannot be cast to futurepack.api.capabilities.INeonEnergyStorage
	at futurepack.api.capabilities.INeonEnergyStorage.canTransferTo(INeonEnergyStorage.java:18) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadEnergyBase(HelperEnergyTransfer.java:89) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.depend.api.helper.HelperEnergyTransfer.powerLowestBlock(HelperEnergyTransfer.java:129) ~[?:1.14.4-28.0.32] {re:classloading}
	at futurepack.common.block.inventory.TileEntityBrennstoffGenerator.func_73660_a(TileEntityBrennstoffGenerator.java:95) ~[?:1.14.4-28.0.32] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```
