### ISSUE TITLE
Complicated Chunk Crash 'cause multithreading

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#649]
Stracktraces:
```
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_221]
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.func_219099_e(SourceFile:48) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219178_f(ChunkManager.java:775) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:474) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) [?:?]
	at net.minecraft.world.World.func_217353_a(World.java:164) [?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) [?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:160) [?:?]
	at net.minecraft.world.World.func_175726_f(World.java:156) [?:?]
	at net.minecraft.world.World.func_175625_s(World.java:840) [?:?]
	at futurepack.depend.api.helper.HelperEnergyTransfer$EnergyUser.isValidBlock(HelperEnergyTransfer.java:241) [?:1.14.4-28.0.51]
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:248) [?:1.14.4-28.0.51]
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadPower(HelperEnergyTransfer.java:291) [?:1.14.4-28.0.51]
	at futurepack.common.block.inventory.TileEntityFlashServer.func_73660_a(TileEntityFlashServer.java:148) [?:1.14.4-28.0.51]
	at net.minecraft.world.World.func_217391_K(World.java:621) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```
```
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_221]
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.func_219099_e(SourceFile:48) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219178_f(ChunkManager.java:775) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:474) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) [?:?]
	at net.minecraft.world.World.func_217353_a(World.java:164) [?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) [?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:160) [?:?]
	at net.minecraft.world.World.func_175726_f(World.java:156) [?:?]
	at net.minecraft.world.World.func_175625_s(World.java:840) [?:?]
	at futurepack.depend.api.helper.HelperEnergyTransfer$EnergyUser.isValidBlock(HelperEnergyTransfer.java:241) [?:1.14.4-28.0.51]
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:248) [?:1.14.4-28.0.51]
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadPower(HelperEnergyTransfer.java:291) [?:1.14.4-28.0.51]
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadEnergyBase(HelperEnergyTransfer.java:104) [?:1.14.4-28.0.51]
	at futurepack.depend.api.helper.HelperEnergyTransfer.powerLowestBlock(HelperEnergyTransfer.java:129) [?:1.14.4-28.0.51]
	at futurepack.common.block.logistic.TileEntityWireBase.func_73660_a(TileEntityWireBase.java:174) [?:1.14.4-28.0.51]
	at net.minecraft.world.World.func_217391_K(World.java:621) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by mcenderdragon** [comment]
DUngeon Core
```
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_221]
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.func_219099_e(SourceFile:48) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219178_f(ChunkManager.java:775) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:474) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) ~[?:?]
	at net.minecraft.world.World.func_217353_a(World.java:164) ~[?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) ~[?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:160) ~[?:?]
	at net.minecraft.world.World.func_175726_f(World.java:156) ~[?:?]
	at futurepack.common.block.misc.TileEntityDungeonCore.run(TileEntityDungeonCore.java:150) ~[?:1.14.4-28.0.51]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_222818_b(SourceFile:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by mcenderdragon** [comment]
Network Manager:
```
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_221]
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.func_219099_e(SourceFile:48) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219178_f(ChunkManager.java:775) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:474) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) ~[?:?]
	at net.minecraft.world.World.func_217353_a(World.java:164) ~[?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) ~[?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:160) ~[?:?]
	at net.minecraft.world.World.func_175726_f(World.java:156) ~[?:?]
	at net.minecraft.world.World.func_175625_s(World.java:840) ~[?:?]
	at futurepack.common.network.NetworkManager$2.isValidBlock(NetworkManager.java:70) ~[?:1.14.4-28.0.49]
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:248) ~[?:1.14.4-28.0.49]
	at futurepack.common.network.NetworkManager.lambda$send$0(NetworkManager.java:114) ~[?:1.14.4-28.0.49]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by mcenderdragon** [comment]
forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/6607

**Comment by mcenderdragon** [comment]
I wrapped everything with chunkExists, so now it works.

**Comment by 88mmAufSfl8** [comment]
congrats
