### ISSUE TITLE
Slots dont give XP

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#650]
```
[06Apr2020 23:33:14.540] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: futurepack.common.block.modification.machines.TileEntityNeonFurnace cannot be cast to net.minecraft.inventory.IRecipeHolder
	at futurepack.common.gui.SlotBaseXPOutput.func_75208_c(SlotBaseXPOutput.java:89) ~[?:1.14.4-28.0.51]
	at futurepack.common.gui.SlotBaseXPOutput.func_190901_a(SlotBaseXPOutput.java:47) ~[?:1.14.4-28.0.51]
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:268) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:1128) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by mcenderdragon** [comment]
fixed in 1.15
