### ISSUE TITLE
Crash when using sprayer

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#660]
https://pastebin.com/FZRwcXhn

**Comment by mcenderdragon** [comment]
Thats an interesting one:
```
java.lang.NullPointerException: Unexpected error
    at futurepack.common.recipes.airbrush.AirbrushRegistry.getColoredBlock(AirbrushRegistry.java:86) ~[?:1.14.4-28.0.75] {re:classloading}
    at futurepack.common.item.tools.ItemAirBrush.func_195939_a(ItemAirBrush.java:97) ~[?:1.14.4-28.0.75] {re:classloading}
    at net.minecraft.item.ItemStack.lambda$onItemUse$0(ItemStack.java:163) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:178) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
```

**Comment by Divineaspect** [comment]
and when I log back in, the block is painted properly and everything.

**Comment by mcenderdragon** [comment]
A: Can this crash be reproduced ?
B: have you jei installed?

**Comment by Divineaspect** [comment]
It's happened more then once, so A: Yes.
B: Yes.

**Comment by mcenderdragon** [comment]
[28.0.126](https://redsnake-games.de/Downloads/fp/fp.php?t=7xSAKIanF5i_zWGF4gS_Rw--) this should fix that.
