### ISSUE TITLE
[1.14] Game crashes when placing modular door next to wardrobe

### ISSUE THREAD

**Issue by SkyProgs** [mcenderdragon/Futurepack-API#662]
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 05.05.20 17:05
Description: Tesselating block model

java.lang.ClassCastException: futurepack.common.block.inventory.TileEntityWardrobe$Large cannot be cast to futurepack.common.block.misc.TileEntityModularDoor
	at futurepack.common.block.misc.BlockModularDoor.func_220053_a(BlockModularDoor.java:87) ~[?:1.14.4-28.0.126] {re:classloading}
	at net.minecraft.block.BlockState.func_215700_a(BlockState.java:202) ~[?:?] {re:classloading}
	at net.minecraft.block.BlockState.func_196954_c(BlockState.java:198) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_196247_c(Block.java:378) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_196951_e(BlockState.java:214) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_200012_i(Block.java:411) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_200015_d(BlockState.java:185) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_200011_d(Block.java:420) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_200016_a(BlockState.java:90) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:145) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:178) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:190) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at futurepack.common.block.misc.BlockModularDoor.func_220053_a(BlockModularDoor.java:87)
	at net.minecraft.block.BlockState.func_215700_a(BlockState.java:202)
	at net.minecraft.block.BlockState.func_196954_c(BlockState.java:198)
	at net.minecraft.block.Block.func_196247_c(Block.java:378)
	at net.minecraft.block.BlockState.func_196951_e(BlockState.java:214)
	at net.minecraft.block.Block.func_200012_i(Block.java:411)
	at net.minecraft.block.BlockState.func_200015_d(BlockState.java:185)
	at net.minecraft.block.Block.func_200011_d(Block.java:420)
	at net.minecraft.block.BlockState.func_200016_a(BlockState.java:90)
	at net.minecraftforge.client.model.pipeline.BlockInfo.updateLightMatrix(BlockInfo.java:145)
	at net.minecraftforge.client.model.pipeline.VertexLighterSmoothAo.updateBlockInfo(VertexLighterSmoothAo.java:178)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:84)

-- Block model being tesselated --
Details:
	Block: Block{futurepack:wardrobe_light_gray_large_1}
	Block location: World: (266,69,-91), Chunk: (at 10,4,5 in 16,-6; contains blocks 256,0,-96 to 271,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
	Block: Block{futurepack:wardrobe_light_gray_large_1}
	Block location: World: (266,69,-91), Chunk: (at 10,4,5 in 16,-6; contains blocks 256,0,-96 to 271,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:60)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['f_roepert'/96843, l='MpServer', x=266.39, y=67.00, z=-88.52]]
	Chunk stats: Client Chunk Cache: 729, 472
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (138,77,-150), Chunk: (at 10,4,10 in 8,-10; contains blocks 128,0,-160 to 143,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5076871 game time, 4633800 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 476325640 bytes (454 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		futurepack-1.14.4-28.0.126.jar Futurepack {futurepack@28.0.126 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: programer_art, vanilla
	Current Language: Deutsch (Deutschland)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
```

**Comment by mcenderdragon** [comment]
Any full block & tile Entity does the crash, no wardrobe required. Lectern also does this...
