### ISSUE TITLE
1.14.4 Some blocks cant be destroyed

### ISSUE THREAD

**Issue by oneandonlyjason** [mcenderdragon/Futurepack-API#701]
Minecraft: 1.14.4 
Forge: 1.14.4-28.2.23

Hello i have a bug where some blocks can not be removed. One block where it occurs is the industrial furnace. When you remove the block it disappears graphically but nothing is dropped. If you try to walk on the block where the furnace was, it does not work, 
and if you reload the world and the block is back.
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5288885/latest.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5288886/FP-Latest.log)

**Comment by mcenderdragon** [comment]
```
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: java.lang.NullPointerException
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at com.mamiyaotaru.voxelmap.persistent.CachedRegion.<init>(CachedRegion.java:147)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1031)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at com.mamiyaotaru.voxelmap.forgemod.TickHandler.onChunkEvent(TickHandler.java:88)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraftforge.eventbus.ASMEventHandler_598_TickHandler_onChunkEvent_ChunkWatchEvent.invoke(.dynamic)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:687)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ChunkManager.func_219199_a(ChunkManager.java:708)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ChunkManager.func_219234_a(ChunkManager.java:813)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ChunkManager.func_219231_b(ChunkManager.java:947)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ServerChunkProvider.func_217226_b(SourceFile:481)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ServerWorld.removeEntityComplete(ServerWorld.java:953)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:997)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:1014)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:1010)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:312)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:900)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:367)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:153)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161)
[27Sep2020 21:10:24.874] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[27Sep2020 21:10:24.875] [Server thread/INFO] [STDERR/]: [com.mamiyaotaru.voxelmap.persistent.PersistentMap:handleChangeInWorld:1062]: 	at java.lang.Thread.run(Unknown Source)
```

This is a VoxelMap crash, open an issue on their bug tracker, I can not do anything to fix this.
