### ISSUE TITLE
[1.16.4] Datapack errors when loading a world more than two times in a session

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#708]
Forge version: 35.1.13
Futurepack version: 21.0.1

When loading a world for the first two times in a session, you just get the warning about experimental features.

However, when you try to load a world for the third time in a session (does not have one you have loaded before, can even be a new world), you are unable to do that because: "Errors in currently selected datapacks prevented the world from loading."

Restarting the client fixes this and you can load a world 2 times with warnings and the third time will again give you a datapack error.

**Comment by mcenderdragon** [comment]
This sounds interesting (and maybe its a Forge bug) can you give me the full log?

**Comment by qrss** [comment]
Sorry, I didn't think to include any logs. Here you go:

[debug.log](https://github.com/mcenderdragon/Futurepack-API/files/5741923/debug.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5741925/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5741926/latest.log)

These logs are taken after I joined a new superflat world 3 times and the third time failed.

The relevant part should be this:

<details>
  <summary>Log snippet</summary>

```
[25Dec2020 12:57:14.878] [Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@2133cc52
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1859) ~[?:?]
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1711) ~[?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
Caused by: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@2133cc52
	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source) ~[?:1.8.0_202]
	at java.util.HashMap.merge(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.tags.TagRegistry.reinjectOptionalTags(TagRegistry.java:89) ~[?:?]
	at net.minecraft.tags.ITagCollectionSupplier.reinjectOptionalTags(ITagCollectionSupplier.java:65) ~[?:?]
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:49) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1858) ~[?:?]
	... 30 more

**Comment by mcenderdragon** [comment]
https://hastebin.com/itiqapagav.properties
Yeah this error feels like a forge bug (or a very weird feature I somehow triggered)
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@2133cc52
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1859) ~[?:?]
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1711) ~[?:?]
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?]
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
Caused by: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@2133cc52
	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source) ~[?:1.8.0_202]
	at java.util.HashMap.merge(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_202]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.tags.TagRegistry.reinjectOptionalTags(TagRegistry.java:89) ~[?:?]
	at net.minecraft.tags.ITagCollectionSupplier.reinjectOptionalTags(ITagCollectionSupplier.java:65) ~[?:?]
	at net.minecraft.tags.NetworkTagManager.lambda$reload$1(NetworkTagManager.java:49) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_202]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1858) ~[?:?]
	... 30 more
```

**Comment by mcenderdragon** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7568

**Comment by mcenderdragon** [comment]
actually was an issue with recipes

**Comment by mcenderdragon** [comment]
PLease try this version [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
I tried opening and closing worlds 6 times and did not encounter any issues, so this seems fixed.
