### ISSUE TITLE
[1.16.4] E-Scanner does not discover all aspects of a block

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#711]
Forge version: 35.1.13
Futurepack version: 21.0.1

I'm having trouble discovering all the aspects in my survival testing playthrough. I have only successfully researched the left column of the aspects.

It turns out that the E-Scanner only gives you the first aspect of a block when you scan it.

For example, scanning a Furnace only gives you Geology, although it is also supposed to give you Thermodynamics and Engineering.

**Comment by mcenderdragon** [comment]
If you look into the log you will most likely find an exception there, this should already be fixed.

**Comment by qrss** [comment]
I'm guessing the exception you mean is this:

```
[25Dec2020 20:35:42.262] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IllegalStateException: Tag forge:ores/silver used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?]
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?]
	at net.minecraft.block.Block.func_203417_a(Block.java:115) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_235714_a_(AbstractBlock.java:684) ~[?:?]
	at futurepack.common.research.ScanningManager$ScanEntry.onBlock(ScanningManager.java:550) ~[futurepack:1.16.4-21.0.1]
	at futurepack.common.research.ScanningManager.doBlock(ScanningManager.java:302) ~[futurepack:1.16.4-21.0.1]
	at futurepack.common.item.tools.ItemEScanner.func_77659_a(ItemEScanner.java:52) ~[futurepack:1.16.4-21.0.1]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

Good job if it is fixed already!

**Comment by mcenderdragon** [comment]
@qrss pleasse try this version [Futurepack-1.16.4-21.0.2](https://www.mediafire.com/file/fzoix8o0kejl9bf/Futurepack-1.16.4-21.0.2.jar/file)

**Comment by qrss** [comment]
It seems that indeed now I get all the intended researches when scanning a block!

One difference compared to earlier versions is that you only get one "Your research(.....) finished" message.

For example, when scanning the furnace I only got the message about Thermodynamics. In 1.15 I would get messages about the other two researches completing as well.

**Comment by mcenderdragon** [comment]
Yeah thats because now it no longer displays in the chat but rather in this extra panel

**Comment by qrss** [comment]
Aha, I didn't notice that difference!

One nice thing about chat is that it logs the messages, although it doesn't really matter that much.

**Comment by qrss** [comment]
Would it be possible to also display the researches that complete in chat?
Maybe as a config option if that seems preferable?

I find that I often miss the message on the screen, especially if I am currently in some menu.
Also, when multiple things are unlocked at once, only one shows up with the current method.

**Comment by mcenderdragon** [comment]
I changed it back to chat.

**Comment by mcenderdragon** [comment]
PLease try this version [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
I can confirm that completed research is showing up in chat again.

This doesn't necessarily mean you have to remove the other message that was showing up, but do whatever feels best for you.
