### ISSUE TITLE
[1.16.4] Using the Telescope does not give you anything

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#719]
Forge version: 35.1.13
Futurepack version: 21.0.2

Using the telescope only put the message "research.planet.discover" in chat and does not give you any items.
This action creates an error message in the log.

[debug.log](https://github.com/mcenderdragon/Futurepack-API/files/5745395/debug.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5745396/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/5745397/latest.log)

```
[28Dec2020 00:15:41.979] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at futurepack.common.spaceships.SpaceshipRegistry.getItemFromPlanet(SpaceshipRegistry.java:182) ~[futurepack:1.16.4-21.0.2]
	at futurepack.common.item.misc.ItemTelescope.func_77659_a(ItemTelescope.java:38) ~[futurepack:1.16.4-21.0.2]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

**Comment by qrss** [comment]
Also, I'm guessing this is a typo: "futurepack:spacecoordinats" ("coordinats" vs "coordinates").

Although it might also be written in another language.

If it is a typo, now would be a good opportunity to fix this, although it doesn't really matter.

**Comment by mcenderdragon** [comment]
I am unable to reproduce this, on which planet/dimension were you when you tried this ?

**Comment by qrss** [comment]
I tried this in the Overworld.

I tested this after making a new world and doing:
`/futurepack research @p unlock all`

Maybe that has something to do with it?

I'll try to research Space Travel in survival and see if the issue still happens.

**Comment by qrss** [comment]
Or perhaps it is already fixed in Dev. Somehow.

**Comment by qrss** [comment]
I tried researching spaceflight related stuff in survival and it the issue was still there.

If it is working fine for you then I'm guessing whatever you did to fix the recipes also fixed the issue with the Telescope.

**Comment by mcenderdragon** [comment]
PLease try this version [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
This seems to be fixed, thanks!
