### ISSUE TITLE
[1.16.5] Error executing task on Server NPE when clicking on a chest that is blocked with a block on top.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#771]
Futurepack-1.16.4-31.1.8176

**Describe the bug**
If you click on a chest with a block on top of it preventing it from opening, you get this NPE on the dedicated server console.

**Logs**
https://gist.github.com/ProsperCraft/36d52a8f70151ce9b4ba48940ddbc239

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: null
        at futurepack.common.gui.inventory.GuiCompositeChest$GenericContainer.<init>(GuiCompositeChest.java:109) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.depend.api.interfaces.ITileInventoryProvider.getInventoryContainer(ITileInventoryProvider.java:14) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.sync.FPGuiHandler.lambda$static$44(FPGuiHandler.java:284) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.sync.FPGuiHandler$Helper.lambda$fromBlockCont$0(FPGuiHandler.java:643) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.sync.FPGuiHandler.lambda$getContainer$114(FPGuiHandler.java:503) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.sync.FPGuiHandler.openGui(FPGuiHandler.java:549) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.sync.FPGuiHandler.openGui(FPGuiHandler.java:566) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        at futurepack.common.block.inventory.BlockCompositeChest.func_225533_a_(BlockCompositeChest.java:35) ~[futurepack:1.16.4-31.1.8176] {re:classloading}
        a
```
