### ISSUE TITLE
Advanced Board Computer says "The Spaceship is ready to jump!" but has no controls.

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#810]
Java    01.08.0261
MC      01.16.0005
Forge   36.01.0058
FP      31.01.8241

**Describe the bug**
The Advanced Board Computer has no main interface. It has a slot for the coordinates but no button to "go"
When I activate it I do get the message, "The Spaceship is ready to jump." but then then this stack trace is logged:

[30Jul2021 12:27:48.964] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index: 32767, Size: 305
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at futurepack.common.research.ResearchManager.getById(ResearchManager.java:45) ~[?:1.16.4-31.1.8241]
	at futurepack.client.research.LocalPlayerResearchHelper.setupResearching(LocalPlayerResearchHelper.java:65) ~[?:1.16.4-31.1.8241]
	at futurepack.common.sync.MessageResearchResponse.consume(MessageResearchResponse.java:77) ~[?:1.16.4-31.1.8241]
	at futurepack.common.sync.FPPacketHandler$$Lambda$5358/133001348.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$8043/372297118.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2893/269257589.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2895/104367332.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/412751586.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$8031/47289326.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$8129/1837847011.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.58.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$441/1885927370.call(Unknown Source) [forge-1.16.5-36.1.58.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**To Reproduce**
1. Have an Advanced Computer on a Generator with bucket of lava.
2. Be in a metal box with FTL, plenty of Thrusters, plenty of Fuel, plenty of NE
3. Click on the Advanced Computer to put the Tyros Coordinates in, and notice that it has no image for the buttons.
4. Click where the buttons should be but nothing happens...
5. Cannot reach Tyros. Cannot get Bioterium.

**Screenshots**

![image](https://user-images.githubusercontent.com/65392871/127691040-c0dcc32e-d59e-42a7-9403-bc6311c2354e.png)

**Additional context**
I thought I'd read the Tech Tree to see if it has new requirements for use but the "Tech Tree is blank" is happening to me again.

**Logs**
Upon request.

**Comment by Yirok42** [comment]
Ignore the comment on the Tech Tree. I read a different issue where Placing a Researcher was mentioned. So I picked one of mine up and put it back down. Tech Tree problem solved (still a bug but easy workaround)

**Comment by Yirok42** [comment]
And possibly that is what fixed the Advanced Board Computer because it now also has an interface. (easy workaround)
I'll reopen if I lose the ability to resolve these issues in game.
