### ISSUE TITLE
Server Crash - Full Log Unknown Reason Traced back to Future Pack

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mcenderdragon/Futurepack-API#83]
I do know after reloading the world is horribly corrupted.
https://gist.github.com/P3rf3ctXZer0/7338ac84a57d04445c4cb389b917af2f

**Comment by mcenderdragon** [comment]
This looks like a damaged Dimenson (Dim3000)

**Comment by mcenderdragon** [comment]
Try out this version http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.18 (if the link is not available try again in 20min)

**Comment by P3rf3ctXZer0** [comment]
It says page doesn't exist

**Comment by P3rf3ctXZer0** [comment]
Can you please upload it here? https://mega.nz

**Comment by mcenderdragon** [comment]
This is our automated build server, so the build is not done yet.

**Comment by mcenderdragon** [comment]
Ok it is availible now.

**Comment by P3rf3ctXZer0** [comment]
no it didn't fix it.


java.lang.RuntimeException: java.io.FileNotFoundException: D:\Video-Games-Collection\Minecraft\MultiMC\instances\Death Plague Gaming-r1.5.6\minecraft\saves\TEST-\DIM30000\FPChunks.dat (The system cannot find the path specified)
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:313)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: D:\Video-Games-Collection\Minecraft\MultiMC\instances\Death Plague Gaming-r1.5.6\minecraft\saves\TEST-\DIM30000\FPChunks.dat (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at futurepack.common.FPChunckManager.onWorldUnload(FPChunckManager.java:169)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_580_FPChunckManager_onWorldUnload_Unload.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	... 6 more

**Comment by P3rf3ctXZer0** [comment]
To create issue load a world; create a dimension using /simpledimensions create "dimensionnamehere"
next do /simpledimensions delete "dimensionsIdnumericalvalue" game crashes.

**Comment by P3rf3ctXZer0** [comment]
Full Crash log

https://gist.github.com/P3rf3ctXZer0/5a6f8237152bf370803862e31cc90791

**Comment by mcenderdragon** [comment]
I need the full CrashReport and Mod name that adds these commands. Also it seems like the mod unregister its dimensions wrong.

**Comment by P3rf3ctXZer0** [comment]
Here is the mod
https://minecraft.curseforge.com/projects/simple-dimensions

Here is the mod source
https://github.com/lumien231/Simple-Dimensions

**Comment by mcenderdragon** [comment]
You are using the wrong version you use the 24.2.17, you need the 24.2.18 I gave you above :)

**Comment by Wugand** [comment]
Please use it from this link: http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.18

**Comment by P3rf3ctXZer0** [comment]
testing now.

**Comment by P3rf3ctXZer0** [comment]
It appears to be fixed thank you :)
