### ISSUE TITLE
Sky rendering broke

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#830]
```
09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: java.lang.NullPointerException
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.client.render.RenderSkyBase.<init>(RenderSkyBase.java:60)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.client.render.RenderSkyAsteroidBelt.<init>(RenderSkyAsteroidBelt.java:17)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.client.render.dimension.DimensionRenderTypeAsteroidBelt.<init>(DimensionRenderTypeAsteroidBelt.java:19)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.common.DistExecutorClient.registerDimensionRenderers(DistExecutorClient.java:465)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.common.DistExecutorClient.postInitClient(DistExecutorClient.java:92)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at futurepack.common.FuturepackMain$$Lambda$4447/1296884710.accept(Unknown Source)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2935/1997319769.invoke(Unknown Source)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2571/486941780.invoke(Unknown Source)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at net.minecraftforge.fml.ModContainer$$Lambda$3315/4121176.run(Unknown Source)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[09:01:07] [Worker-Main-13/INFO]: [futurepack.client.render.RenderSkyBase:<init>:81]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mcenderdragon** [comment]
seems to be special, with something else.
