### ISSUE TITLE
[1.18.2/33.0.7268]Crash when clicking on Neon Engine in Escanner

### ISSUE THREAD

**Issue by gomamon282** [mcenderdragon/Futurepack-API#874]
**Describe the bug**
Something caused the game to crash when I clicked on the Neon engine in the Escanner

**To Reproduce**
1. Open the scanner UI
2. Click on 'Neon Engine'
3. Game crashed

**Screenshots**
N/A

**Additional context**
N/A

**Version**
Minecraft Version:1.18.2
Forge Version:40.1.0
Futurepack Version: 33.0.7268

**Logs**
https://gist.github.com/gomamon282/0a9a0a2fc34926f8c651d8747a8fcf37

**Comment by mcenderdragon** [comment]
```
[304��2022 18:59:38.940] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseReleased event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:535) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2330!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2326!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2330!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2350!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "futurepack.depend.api.interfaces.IGuiComponent.init(int, net.minecraft.client.gui.screens.Screen)" because "com" is null
	at futurepack.common.gui.escanner.GuiScannerPageBase.m_7856_(GuiScannerPageBase.java:45) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:423) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:918) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at futurepack.common.gui.escanner.GuiResearchMainOverview.openResearchText(GuiResearchMainOverview.java:263) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiResearchTreePage.m_6348_(GuiResearchTreePage.java:229) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiResearchMainOverview.m_6348_(GuiResearchMainOverview.java:128) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
```

caused by.

````[304��2022 18:59:25.293] [Render thread/ERROR] [futurepack/]: There was an error in the constructor of an gui component
[304��2022 18:59:25.293] [Render thread/ERROR] [futurepack/CATCHING]: Catching
net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: OreDict:ingotMagnetite
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at futurepack.depend.api.helper.HelperJSON.getItemFromJSON(HelperJSON.java:91) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.ComponentCrafting.<init>(ComponentCrafting.java:95) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at futurepack.common.research.ScannerPageResearch.lambda$registerComponent$0(ScannerPageResearch.java:187) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.research.ScannerPageResearch.getComponetsFromJSON(ScannerPageResearch.java:118) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.research.ScannerPageResearch.getComponetsFromName(ScannerPageResearch.java:83) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiScannerPageResearch.<init>(GuiScannerPageResearch.java:11) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiResearchMainOverview.openResearchText(GuiResearchMainOverview.java:257) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiResearchTreePage.m_6348_(GuiResearchTreePage.java:229) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at futurepack.common.gui.escanner.GuiResearchMainOverview.m_6348_(GuiResearchMainOverview.java:128) ~[Futurepack-1.18.2-33.0.7268.jar%23175!/:1.18.2-33.0.7268]
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2330!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2326!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2330!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23320!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2350!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]```

**Comment by belathus** [comment]
I had a similar crash when clicking on the biopolymer entry: https://gist.github.com/belathus/e699ebea3135ac5686e34f8fcf3df410

**Comment by mcenderdragon** [comment]
> I had a similar crash when clicking on the biopolymer entry: https://gist.github.com/belathus/e699ebea3135ac5686e34f8fcf3df410

full log please - this error is cuased by something else that happened earlier.

**Comment by mcenderdragon** [comment]
ahh ok this is caused becuase alot of text arent updated for pt_br and zh_cn

**Comment by mcenderdragon** [comment]
Affected files
### pt_BR
```
production.ind.reduktion.json (16 matches)
production.industrieofen.json (4 matches)
production.neonfurnace.json (2 matches)
production.nind.keramik.json (3 matches)
production.nind.linse.r.json (2 matches)
production.nind.magnet.json (4 matches)
production.nind.quantanium.json (4 matches)
production.nind.reduktion.json (12 matches)
production.nind.reloaded.json (4 matches)
production.nind.wakurum.json (3 matches)
production.optibench.json (3 matches)
production.recycler.analyzer.json (2 matches)
production.recycler.lasercutter.json
production.recycler.shredder.json (4 matches)
production.supercrusher.json (4 matches)
production.zent.extraction1.json (4 matches)
production.zent.neon.json (3 matches)
production.zent.rare.json (6 matches)
scanner.json (2 matches)
space.claime.json
space.fuel.json (6 matches)
space.gravity.json (6 matches)
space.navcord.menelaus.json (2 matches)
space.navcord.tyros.json (2 matches)
space.tank.json (4 matches)
space.thruster.json (5 matches)
tools.grenade.he.json (5 matches)
tools.grenade.plasma.json (6 matches)
tools.hologramm.json (6 matches)
tools.logistik_editor.json (2 matches)
tools.plasma.json (3 matches)
tools.sauerstofftank.json (3 matches)
tools.scrench.json (2 matches)
unreach.laserbow.json (3 matches)
upgradeT3.json (2 matches)
util.json (30 matches)
```
### zh_cn
```
assembly_chip.json
chips.cooler.json (5 matches)
chips.watercooler.json (3 matches)
deco.glass.json (5 matches)
deco.neonlamp.json (2 matches)
deco.plasmalamp.json (3 matches)
deco.wardrobe.json (24 matches)
energy.infusion.json (2 matches)
energy.ionen.json
energy.solar.json (2 matches)
energy.wasser_turbine.json (2 matches)
log.battery.cell.json (2 matches)
log.battery.compact.json
log.battery.large.json (6 matches)
log.battery.neon.json (5 matches)
log.laser.json (2 matches)
production.nind.linse.g.json (2 matches)
production.partpress.json (12 matches)
space.dronestation.json (4 matches)
space.miner.json (2 matches)
space.turret.killer.json
tools.grabling.json (4 matches)
tools.grenadelauncher.json (2 matches)
tools.plasma.json (3 matches)
upgradeT3.json (2 matches)
```
