### ISSUE TITLE
Minecraft Crashed when try to go to the dungeon

### ISSUE THREAD

**Issue by Dark-Matter-X** [mcenderdragon/Futurepack-API#876]
**Describe the bug**
When I warped to dungeon dimension, minecraft crashed.

**To Reproduce**
1. Enter the Dungeon
2. See error
3. Reentering crashed world causes same issue

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.14
Futurepack Version: 33.0.7268

**Logs**
    https://gist.github.com/Dark-Matter-X/dfe9aba89a14dcd1e78ba97d4ed75dc6

**Comment by mcenderdragon** [comment]
```

java.lang.RuntimeException: Provider futurepack.common.CapProviderRFSupport$RFCapabilityProvider.getCapability() returned null; return LazyOptional.empty() instead!
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:94) ~[forge-1.18.2-40.1.14-universal.jar%2389!/:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183) ~[forge-1.18.2-40.1.14-universal.jar%2389!/:?] {re:computing_frames,re:mixin,re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.getCapability(TileEntityModificationBase.java:219) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.common.block.multiblock.TileEntityDeepCoreMinerMain.getCapability(TileEntityDeepCoreMinerMain.java:620) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.getNeonCap(TileEntityModificationBase.java:188) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.common.block.modification.TileEntityModificationBase.getCapability(TileEntityModificationBase.java:217) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.common.block.multiblock.TileEntityDeepCoreMinerMain.getCapability(TileEntityDeepCoreMinerMain.java:620) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadEnergyBase(HelperEnergyTransfer.java:71) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.depend.api.helper.HelperEnergyTransfer.powerLowestBlock(HelperEnergyTransfer.java:130) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.common.block.logistic.TileEntityWireBase.tickServer(TileEntityWireBase.java:143) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at futurepack.api.helper.HelperTileEntities.lambda$createServerTicker$1(HelperTileEntities.java:31) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

```

Disabling the RF support should stop the crash.

**Comment by Dark-Matter-X** [comment]
> ```
> 
> java.lang.RuntimeException: Provider futurepack.common.CapProviderRFSupport$RFCapabilityProvider.getCapability() returned null; return LazyOptional.empty() instead!
> 	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:94) ~[forge-1.18.2-40.1.14-universal.jar%2389!/:?] {re:classloading}
> 	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183) ~[forge-1.18.2-40.1.14-universal.jar%2389!/:?] {re:computing_frames,re:mixin,re:classloading}
> 	at futurepack.common.block.modification.TileEntityModificationBase.getCapability(TileEntityModificationBase.java:219) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.common.block.multiblock.TileEntityDeepCoreMinerMain.getCapability(TileEntityDeepCoreMinerMain.java:620) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.common.block.modification.TileEntityModificationBase.getNeonCap(TileEntityModificationBase.java:188) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.common.block.modification.TileEntityModificationBase.getCapability(TileEntityModificationBase.java:217) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.common.block.multiblock.TileEntityDeepCoreMinerMain.getCapability(TileEntityDeepCoreMinerMain.java:620) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadEnergyBase(HelperEnergyTransfer.java:71) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.depend.api.helper.HelperEnergyTransfer.powerLowestBlock(HelperEnergyTransfer.java:130) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.common.block.logistic.TileEntityWireBase.tickServer(TileEntityWireBase.java:143) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at futurepack.api.helper.HelperTileEntities.lambda$createServerTicker$1(HelperTileEntities.java:31) ~[Futurepack-1.18.2-33.0.7268.jar%2364!/:1.18.2-33.0.7268] {re:classloading}
> 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading}
> 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading}
> 	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:zombieawareness.mixins.json:MixinPlaySound,pl:mixin:APP:zombieawareness.mixins.json:MixinLevelEvent,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at java.lang.Thread.run(Thread.java:833) [?:?] {}
> ```
> 
> Disabling the RF support should stop the crash.

Thanks for the help!
It works again

**Comment by mcenderdragon** [comment]
keeping this open as it should not crash and the config change is only a temp fix.

**Comment by mcenderdragon** [comment]
supersedded by https://github.com/mcenderdragon/Futurepack-API/issues/898
