### ISSUE TITLE
[1.18.2] Weird error in server logs

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#881]
**Describe the bug**
Weird error about dungeon manager in server logs. 

see log section

**To Reproduce**
1. Start Server
2. Watch logs
**Screenshots**

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.19
Futurepack Version:  Latest Beta on CF 5/20/22

**Logs**
Full log: https://gist.github.com/itsdinkd/de406912ff7c81dce51ee2c566264285

Snippet:
```java
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:167)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.dim.structures.ManagerDungeonStructures.get(ManagerDungeonStructures.java:208)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$StructureEntry.<init>(DungeonFeatureConfig.java:100)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.world.gen.feature.DungeonFeatureConfig$Builder.addEntryAuto(DungeonFeatureConfig.java:70)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.createConfiguredTcDungeonFeature(WorldGenRegistry.java:169)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.genFeatureTecDungeon(WorldGenRegistry.java:210)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.register(WorldGenRegistry.java:120)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.WorldGenRegistry.init(WorldGenRegistry.java:57)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.init(FuturepackMain.java:202)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.19/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/fmlcore@1.18.2-40.1.19/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        ```

**Comment by mcenderdragon** [comment]
yeah forge remvoed the modjar URL thing out of nowhere adn it ewas used as a backup to load stuff - gotta love then forge remvoes things beczase they think its no longer needed/used...

**Comment by itsdinkd** [comment]
Yep. I'm more of a fabric person myself than forge, the way things are done
over there are much better.

**Comment by mcenderdragon** [comment]
removed/fixed in https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3811830
