### ISSUE TITLE
Crash with Dynamic Surroundings and possibly other mods

### ISSUE THREAD

**Issue by Airisii** [mcenderdragon/Futurepack-API#893]
Im using the latest 1.12.2 version of the mod and forge and it crashes with adding futurepack. 
Crash Log: https://pastebin.com/40BXszyu

**Comment by mcenderdragon** [comment]
Dynmic surroundigs crashed not futurepack because:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from §3Dynamic Surroundings (dsurround)
Caused by: java.lang.NoClassDefFoundError: org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironState (initialization failure)
...
...
...
Caused by: java.lang.NullPointerException
    at org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironStateData.<init>(EnvironStateHandler.java:72)
    at org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironState.<clinit>(EnvironStateHandler.java:99)
    at org.orecruncher.dsurround.event.WorldEventDetector.notifyBlockUpdate(WorldEventDetector.java:64)
    at net.minecraft.world.World.notifyBlockUpdate(World.java:432)
```

they seems to somehow interact with our Airbrush Recipes. Also 1.12 will not receive more updates - sorry. Maybe Dyn Surroundings has a fix for this.

**Comment by mcenderdragon** [comment]
As we cant fix this issue I will close this.
