### ISSUE TITLE
Enabling RF support caussing crash

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#898]
it crashes when enabled in the config.

**Comment by mcenderdragon** [comment]
```
java.lang.RuntimeException: Provider futurepack.common.CapProviderRFSupport$RFCapabilityProvider.getCapability() returned null; return LazyOptional.empty() instead!
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:94) ~[forge-1.18.2-40.1.20-universal.jar%23392!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183) ~[forge-1.18.2-40.1.20-universal.jar%23392!/:?]
	at futurepack.common.block.modification.TileEntityModificationBase.getCapability(TileEntityModificationBase.java:219) ~[Futurepack-1.18.2-33.0.7327.jar%23190!/:1.18.2-33.0.7327]
	at futurepack.common.block.modification.TileEntityFluidPump.getCapability(TileEntityFluidPump.java:87) ~[Futurepack-1.18.2-33.0.7327.jar%23190!/:1.18.2-33.0.7327]
	at mekanism.common.util.CapabilityUtils.getCapability(CapabilityUtils.java:21) ~[Mekanism-1.18.2-10.2.2.462.jar%23253!/:10.2.2]
	at mekanism.common.integration.lookingat.LookingAtUtils.addInfo(LookingAtUtils.java:77) ~[Mekanism-1.18.2-10.2.2.462.jar%23253!/:10.2.2]
	at mekanism.common.integration.lookingat.hwyla.HwylaDataProvider.appendServerData(HwylaDataProvider.java:38) ~[Mekanism-1.18.2-10.2.2.462.jar%23253!/:10.2.2]
	at mekanism.common.integration.lookingat.hwyla.HwylaDataProvider.appendServerData(HwylaDataProvider.java:19) ~[Mekanism-1.18.2-10.2.2.462.jar%23253!/:10.2.2]
	at 
```

**Comment by mcenderdragon** [comment]
disabling it in the configs fies it unitl I push out the next update.
