### ISSUE TITLE
[1.18.2-33.0.7457] -  Crash on tyros

### ISSUE THREAD

**Issue by luisbrandao** [mcenderdragon/Futurepack-API#928]
Just updated the mod and got there. Sometyhing cant be generated on the map...

```
[26set.2022 13:28:55.016] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 700
[26set.2022 13:28:55.016] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 710
[26set.2022 13:28:55.017] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 720
[26set.2022 13:28:55.018] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 730
[26set.2022 13:28:55.019] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 740
[26set.2022 13:28:55.019] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 750
[26set.2022 13:28:55.020] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 640
[26set.2022 13:28:55.021] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 640
[26set.2022 13:28:55.168] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 614
[26set.2022 13:28:55.172] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 624
[26set.2022 13:28:55.173] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 634
[26set.2022 13:28:55.174] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 644
[26set.2022 13:28:55.175] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 654
[26set.2022 13:28:55.175] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 664 
[26set.2022 13:28:55.176] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 674
[26set.2022 13:28:55.177] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 684
[26set.2022 13:28:55.178] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 694
[26set.2022 13:28:55.179] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 704 
[26set.2022 13:28:55.207] [Server thread/WARN] [futurepack/]: [Worldgen][futurepack:tyros] Canceled a possible stackoverflow: 730
```
```
[26set.2022 13:28:55.326] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for futurepack:tyros
net.minecraft.ReportedException: Feature placement
        at net.minecraft.server.level.ChunkMap.m_203056_(ChunkMap.java:602) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:1269) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:1165) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_6325_(Level.java:2081) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_8055_(Level.java:2573) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60705_(BlockBehaviour.java:653) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:247) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_6933_(Level.java:214) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_7731_(Level.java:178) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_46597_(Level.java:294) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.block.LiquidBlock.m_54696_(LiquidBlock.java:139) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.block.LiquidBlock.m_6861_(LiquidBlock.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60690_(BlockBehaviour.java:640) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_46586_(Level.java:350) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_46672_(Level.java:305) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.server.level.ServerLevel.m_6289_(ServerLevel.java:1421) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:238) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_6933_(Level.java:214) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.Level.m_7731_(Level.java:178) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
```
```
Caused by: java.lang.IllegalStateException: Tried to biome check an unregistered feature
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_191567_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_183168_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacementFilter.m_183381_(PlacementFilter.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191801_(PlacedFeature.java:50) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191782_(PlacedFeature.java:40) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
Caused by: java.lang.IllegalStateException: Tried to biome check an unregistered feature
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_191567_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_183168_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacementFilter.m_183381_(PlacementFilter.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191801_(PlacedFeature.java:50) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191782_(PlacedFeature.java:40) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
```
```
Caused by: java.lang.IllegalStateException: Tried to biome check an unregistered feature
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_191567_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.BiomeFilter.m_183168_(BiomeFilter.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacementFilter.m_183381_(PlacementFilter.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191801_(PlacedFeature.java:50) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
        at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191782_(PlacedFeature.java:40) ~[server-1.18.2-20220404.173914-srg.jar%23157!/:?]
```

**Comment by mcenderdragon** [comment]
does this also happen with just futurepack installed ?

**Comment by luisbrandao** [comment]
It didnt crash with only Futurepack :/

I also notice:
No arcs on manelus
No plants on tyros (tried 2 diferent seeds... only stony_desert showing up)
(both happened with only futurepak)

**Comment by luisbrandao** [comment]
Crash is gone on 1.18.2-33.0.7465
