### ISSUE TITLE
[1.18.2] Server NullPointer on startup

### ISSUE THREAD

**Issue by Shadowrs** [mcenderdragon/Futurepack-API#956]
**Describe the bug**
Just an NPE on startup idk what effects it has

**To Reproduce**
Steps to reproduce the behaviour:
Start server

**Screenshots**

**Additional context**
All the mods 7 Modpack with some extra mods added by myself

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.2.0-
Futurepack Version: Futurepack-1.18.2-33.0.7482

**Logs**
For some reason its not in debug.log latest.log or FPlatest.log, I just saw it in the console

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.crafting.Ingredient.m_43947_()" because the return value of "net.minecraft.world.item.Tier.m_6282_()" is null
        at TRANSFORMER/futurepack@033.0.7482/futurepack.common.recipes.recycler.FPRecyclerTimeManipulatorManager.isItemRepairable(FPRecyclerTimeManipulatorManager.java:262)
        at TRANSFORMER/futurepack@033.0.7482/futurepack.common.recipes.recycler.FPRecyclerTimeManipulatorManager$1.lambda$run$0(FPRecyclerTimeManipulatorManager.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
```

**Comment by mcenderdragon** [comment]
seems like another mod has not correctly implemneted the Tier class (and uses null instead of itemStack.EMPTY)

**Comment by mcenderdragon** [comment]
shopuld be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/4555761
