### ISSUE TITLE
[1.18.2] LootTables: Couldn't parse loot table futurepack:blocks/network_modem

### ISSUE THREAD

**Issue by Shadowrs** [mcenderdragon/Futurepack-API#957]
**Describe the bug**
`com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'futurepack:network_modem'`

There is no `\Futurepack\src\main\resources\data\futurepack\loot_tables\blocks\network_modem.json` in the 1.18 branch on gitlab, so I'm not sure where the reference is coming from.

**To Reproduce**
Start server

**Screenshots**

**Additional context**
I Added futurepack after the world was first created, as a new mod addition to a the All The Mods 7 modpack. If that has an affect.
If this error only occurs when you add a mod to an already-existing modpack world, a custom exception with feedback explaining that sounds like a good feature request we could submit to Forge on github.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.2.0-
Futurepack Version: Futurepack-1.18.2-33.0.7482

**Logs**
use control-f its a big lol with parse errors of another mod I added after world was created
https://pastebin.com/6SW92J2T

```

[19Jan2023 12:10:19.169] [Worker-Main-12/ERROR] [net.minecraft.world.level.storage.loot.LootTables/]: Couldn't parse loot table futurepack:blocks/network_modem
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'futurepack:network_modem'
	at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:130) ~[server-1.18.2-20220404.173914-srg.jar%23382!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:130) ~[server-1.18.2-20220404.173914-srg.jar%23382!/:?]
	at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:138) ~[server-1.18.2-20220404.173914-srg.jar%23382!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23382!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[server-1.18.2-20220404.173914-srg.jar%23382!/:?]
```

**Comment by mcenderdragon** [comment]
this is intened behauvier and part of the mod combatilbity with Computercraft. you can mark tags as optional which will then produce this crash, which imo is stupid but oh well.
