### ISSUE TITLE
Random Spam in 1.18.2 Server

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#985]
**Describe the bug**
Receiving tons of spam in a dedicated server about an error that is being suppressed stemming from Future Pack

**To Reproduce**
Not sure how to reproduce. just reporting this so its known.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.2.8
Futurepack Version: 33.0.7544

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:

```
[19:49:40] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@3f84cd84, suppressing error
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "key" is null
        at java.util.EnumMap.typeCheck(EnumMap.java:736) ~[?:?] {re:mixin}
        at java.util.EnumMap.put(EnumMap.java:264) ~[?:?] {re:mixin}
        at java.util.EnumMap.put(EnumMap.java:78) ~[?:?] {re:mixin}
        at java.util.Map.computeIfAbsent(Map.java:1055) ~[?:?] {re:mixin}
        at futurepack.common.CapProviderRFSupport$RFCapabilityProvider.getCapability(CapProviderRFSupport.java:51) ~[Futurepack-1.18.2-33.0.7544.jar%23179!/:1.18.2-33.0.7544] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:89) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:183) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:34) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
        at snownee.jade.addon.forge.ForgeCapabilityProvider.appendServerData(ForgeCapabilityProvider.java:93) ~[Jade-1.18.2-forge-5.3.1.jar%23207!/:5.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
        at snownee.jade.addon.forge.ForgeCapabilityProvider.appendServerData(ForgeCapabilityProvider.java:29) ~[Jade-1.18.2-forge-5.3.1.jar%23207!/:5.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
        at mcp.mobius.waila.network.RequestTilePacket$Handler.lambda$onMessage$0(RequestTilePacket.java:62) ~[Jade-1.18.2-forge-5.3.1.jar%23207!/:5.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at mcp.mobius.waila.network.RequestTilePacket$Handler.onMessage(RequestTilePacket.java:46) ~[Jade-1.18.2-forge-5.3.1.jar%23207!/:5.3.1] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:connectivity.mixins.json:SimpleChannelMixin,pl:mixin:A}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
        at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.2.8-universal.jar%23400!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1440) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:connectivity.mixins.json:networkstats.CCustomPayloadPacketNameMixin,pl:mixin:A}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23395!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```

**Comment by Dinerell** [comment]
Can you look out for any use of an RF-Converter, try to remove any block beside it until the the error doesn't occur anymore?

**Comment by mcenderdragon** [comment]
snownee.jade.addon.forge.ForgeCapabilityProvider is calling futurepack functions with null, which we dont support, hence the error.
